[package]
name = "bitview_plugin_constants"
description = "The constant series plugin for Bitview"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage = "https://bitview.dev"
repository.workspace = true

[dependencies]
bitview_primitives = { workspace = true, features = ["storage"] }
bitview_transforms = { workspace = true }
bitview_vecs = { workspace = true }
bitview_plugin = { workspace = true }
bitview_traversable = { workspace = true }
brk_types = { workspace = true, features = ["storage"] }
