// Auto-generated by bitview_bindgen. Do not edit.

use crate::{command::Command, parameter::Parameter, request_body::RequestBody};

#[rustfmt::skip]
pub(crate) static COMMANDS: &[Command] = &[
    Command {
        name: "get-address",
        method: "GET",
        path: "/api/address/{address}",
        summary: "Address information",
        description: "Retrieve address information including current balance and transaction counts. Supports all standard Bitcoin address types (P2PKH, P2SH, P2WPKH, P2WSH, P2TR).\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-address)*",
        path_parameters: &[
            Parameter { api_name: "address", name: "address", required: true, value_name: "Addr", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-address-confirmed-txs",
        method: "GET",
        path: "/api/address/{address}/txs/chain",
        summary: "Address confirmed transactions",
        description: "Get the first 25 confirmed transactions for an address. For pagination, request `GET /api/address/{address}/txs/chain/{after_txid}` with the last returned txid.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-address-transactions-chain)*",
        path_parameters: &[
            Parameter { api_name: "address", name: "address", required: true, value_name: "Addr", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-address-confirmed-txs-after",
        method: "GET",
        path: "/api/address/{address}/txs/chain/{after_txid}",
        summary: "Address confirmed transactions (paginated)",
        description: "Get the next 25 confirmed transactions strictly older than `after_txid` (Esplora-canonical pagination form, matches mempool.space).\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-address-transactions-chain)*",
        path_parameters: &[
            Parameter { api_name: "address", name: "address", required: true, value_name: "Addr", repeatable: false, description: None },
            Parameter { api_name: "after_txid", name: "after-txid", required: true, value_name: "Txid", repeatable: false, description: Some("Last txid from the previous page (return transactions strictly older than this)") },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-address-hash-prefix-matches",
        method: "GET",
        path: "/api/address/hash-prefix/{addr_type}/{prefix}",
        summary: "Address hash-prefix matches",
        description: "Find addresses by address type and by the first 1-16 hex nibbles of RapidHash v3 over the raw address payload bytes. Intended for privacy-preserving client-side wallet discovery without sending raw addresses or xpubs. Fetch metadata with `GET /api/address/{address}`.",
        path_parameters: &[
            Parameter { api_name: "addr_type", name: "addr-type", required: true, value_name: "OutputType", repeatable: false, description: None },
            Parameter { api_name: "prefix", name: "prefix", required: true, value_name: "string", repeatable: false, description: Some("First 1–16 hexadecimal nibbles of the RapidHash v3 hash over the raw\naddress payload bytes.") },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-address-mempool-txs",
        method: "GET",
        path: "/api/address/{address}/txs/mempool",
        summary: "Address mempool transactions",
        description: "Get unconfirmed transactions for an address from the mempool, newest first (up to 50).\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-address-transactions-mempool)*",
        path_parameters: &[
            Parameter { api_name: "address", name: "address", required: true, value_name: "Addr", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-address-txs",
        method: "GET",
        path: "/api/address/{address}/txs",
        summary: "Address transactions",
        description: "Get transaction history for an address, newest first. Returns up to 50 mempool transactions plus a confirmed page sized to fill the response to 50 total (chain floor of 25, so 25-50 confirmed depending on mempool weight). To paginate further confirmed history, request `GET /api/address/{address}/txs/chain/{after_txid}` with the last returned txid.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-address-transactions)*",
        path_parameters: &[
            Parameter { api_name: "address", name: "address", required: true, value_name: "Addr", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-address-utxos",
        method: "GET",
        path: "/api/address/{address}/utxo",
        summary: "Address UTXOs",
        description: "Get unspent transaction outputs (UTXOs) for an address. Returns txid, vout, value, and confirmation status for each UTXO.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-address-utxo)*",
        path_parameters: &[
            Parameter { api_name: "address", name: "address", required: true, value_name: "Addr", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-api",
        method: "GET",
        path: "/api.json",
        summary: "Compact OpenAPI specification",
        description: "Compact OpenAPI specification optimized for LLM consumption. Removes redundant fields while preserving essential API information. The full specification is available at `GET /openapi.json`.",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-block",
        method: "GET",
        path: "/api/block/{hash}",
        summary: "Block information",
        description: "Retrieve block information by block hash. Returns block metadata including height, timestamp, difficulty, size, weight, and transaction count.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-block)*",
        path_parameters: &[
            Parameter { api_name: "hash", name: "hash", required: true, value_name: "BlockHash", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-block-by-height",
        method: "GET",
        path: "/api/block-height/{height}",
        summary: "Block hash by height",
        description: "Retrieve the block hash at a given height. Returns the hash as plain text.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-block-height)*",
        path_parameters: &[
            Parameter { api_name: "height", name: "height", required: true, value_name: "Height", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-block-by-timestamp",
        method: "GET",
        path: "/api/v1/mining/blocks/timestamp/{timestamp}",
        summary: "Block by timestamp",
        description: "Find the block closest to a given UNIX timestamp.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-block-timestamp)*",
        path_parameters: &[
            Parameter { api_name: "timestamp", name: "timestamp", required: true, value_name: "Timestamp", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-block-fee-rates",
        method: "GET",
        path: "/api/v1/mining/blocks/fee-rates/{time_period}",
        summary: "Block fee rates",
        description: "Get block fee rate percentiles (min, 10th, 25th, median, 75th, 90th, max) for a time period. Valid periods: `24h`, `3d`, `1w`, `1m`, `3m`, `6m`, `1y`, `2y`, `3y`.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-block-feerates)*",
        path_parameters: &[
            Parameter { api_name: "time_period", name: "time-period", required: true, value_name: "TimePeriod", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-block-fees",
        method: "GET",
        path: "/api/v1/mining/blocks/fees/{time_period}",
        summary: "Block fees",
        description: "Get average total fees per block for a time period. Valid periods: `24h`, `3d`, `1w`, `1m`, `3m`, `6m`, `1y`, `2y`, `3y`.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-block-fees)*",
        path_parameters: &[
            Parameter { api_name: "time_period", name: "time-period", required: true, value_name: "TimePeriod", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-block-header",
        method: "GET",
        path: "/api/block/{hash}/header",
        summary: "Block header",
        description: "Returns the hex-encoded 80-byte block header.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-block-header)*",
        path_parameters: &[
            Parameter { api_name: "hash", name: "hash", required: true, value_name: "BlockHash", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-block-raw",
        method: "GET",
        path: "/api/block/{hash}/raw",
        summary: "Raw block",
        description: "Returns the raw block data in binary format.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-block-raw)*",
        path_parameters: &[
            Parameter { api_name: "hash", name: "hash", required: true, value_name: "BlockHash", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-block-rewards",
        method: "GET",
        path: "/api/v1/mining/blocks/rewards/{time_period}",
        summary: "Block rewards",
        description: "Get average coinbase reward (subsidy + fees) per block for a time period. Valid periods: `24h`, `3d`, `1w`, `1m`, `3m`, `6m`, `1y`, `2y`, `3y`.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-block-rewards)*",
        path_parameters: &[
            Parameter { api_name: "time_period", name: "time-period", required: true, value_name: "TimePeriod", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-block-sizes-weights",
        method: "GET",
        path: "/api/v1/mining/blocks/sizes-weights/{time_period}",
        summary: "Block sizes and weights",
        description: "Get average block sizes and weights for a time period. Valid periods: `24h`, `3d`, `1w`, `1m`, `3m`, `6m`, `1y`, `2y`, `3y`.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-sizes-weights)*",
        path_parameters: &[
            Parameter { api_name: "time_period", name: "time-period", required: true, value_name: "TimePeriod", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-block-status",
        method: "GET",
        path: "/api/block/{hash}/status",
        summary: "Block status",
        description: "Retrieve the status of a block. Returns whether the block is in the best chain and, if so, its height and the hash of the next block.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-block-status)*",
        path_parameters: &[
            Parameter { api_name: "hash", name: "hash", required: true, value_name: "BlockHash", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-block-template",
        method: "GET",
        path: "/api/v1/mempool/block-template",
        summary: "Projected next block template",
        description: "Bitcoin Core's `getblocktemplate` selection: full transaction bodies in GBT order with aggregate stats. The returned `hash` is an opaque content token; pass it to `GET /api/v1/mempool/block-template/diff/{hash}` to fetch deltas instead of refetching the whole template.",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-block-template-diff",
        method: "GET",
        path: "/api/v1/mempool/block-template/diff/{hash}",
        summary: "Block template diff since hash",
        description: "Delta of the projected next block since `<hash>`. `order` is the full new template in order: each entry is either a number (index into the prior template the client cached at `<hash>`) or a transaction object (new body to insert at this position). Walk `order` once to rebuild; `removed` is a convenience list of txids that left so clients can evict cached bodies. After applying, use the response `hash` as `<hash>` on the next call to keep iterating. Returns `404` when `<hash>` has aged out of server history; clients should fall back to `GET /api/v1/mempool/block-template`.",
        path_parameters: &[
            Parameter { api_name: "hash", name: "hash", required: true, value_name: "NextBlockHash", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-block-tip-hash",
        method: "GET",
        path: "/api/blocks/tip/hash",
        summary: "Block tip hash",
        description: "Returns the hash of the last block.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-block-tip-hash)*",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-block-tip-height",
        method: "GET",
        path: "/api/blocks/tip/height",
        summary: "Block tip height",
        description: "Returns the height of the last block.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-block-tip-height)*",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-block-txid",
        method: "GET",
        path: "/api/block/{hash}/txid/{index}",
        summary: "Transaction ID at index",
        description: "Retrieve a single transaction ID at a specific index within a block. Returns plain text txid.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-block-transaction-id)*",
        path_parameters: &[
            Parameter { api_name: "hash", name: "hash", required: true, value_name: "BlockHash", repeatable: false, description: Some("Bitcoin block hash") },
            Parameter { api_name: "index", name: "index", required: true, value_name: "BlockTxIndex", repeatable: false, description: Some("Transaction index within the block (0-based)") },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-block-txids",
        method: "GET",
        path: "/api/block/{hash}/txids",
        summary: "Block transaction IDs",
        description: "Retrieve all transaction IDs in a block. Returns an array of txids in block order.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-block-transaction-ids)*",
        path_parameters: &[
            Parameter { api_name: "hash", name: "hash", required: true, value_name: "BlockHash", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-block-txs",
        method: "GET",
        path: "/api/block/{hash}/txs",
        summary: "Block transactions",
        description: "Retrieve transactions in a block by block hash. Returns up to 25 transactions starting from index 0.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-block-transactions)*",
        path_parameters: &[
            Parameter { api_name: "hash", name: "hash", required: true, value_name: "BlockHash", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-block-txs-from-index",
        method: "GET",
        path: "/api/block/{hash}/txs/{start_index}",
        summary: "Block transactions (paginated)",
        description: "Retrieve transactions in a block by block hash, starting from the specified index. Returns up to 25 transactions at a time.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-block-transactions)*",
        path_parameters: &[
            Parameter { api_name: "hash", name: "hash", required: true, value_name: "BlockHash", repeatable: false, description: Some("Bitcoin block hash") },
            Parameter { api_name: "start_index", name: "start-index", required: true, value_name: "BlockTxIndex", repeatable: false, description: Some("Starting transaction index within the block (0-based)") },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-block-v1",
        method: "GET",
        path: "/api/v1/block/{hash}",
        summary: "Block (v1)",
        description: "Returns block details with extras by hash.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-block-v1)*",
        path_parameters: &[
            Parameter { api_name: "hash", name: "hash", required: true, value_name: "BlockHash", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-blocks",
        method: "GET",
        path: "/api/blocks",
        summary: "Recent blocks",
        description: "Retrieve the last 10 blocks. Returns block metadata for each block.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-blocks)*",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-blocks-from-height",
        method: "GET",
        path: "/api/blocks/{height}",
        summary: "Blocks from height",
        description: "Retrieve up to 10 blocks going backwards from the given height. For example, height=100 returns blocks 100, 99, 98, ..., 91. Height=0 returns only block 0.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-blocks)*",
        path_parameters: &[
            Parameter { api_name: "height", name: "height", required: true, value_name: "Height", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-blocks-v1",
        method: "GET",
        path: "/api/v1/blocks",
        summary: "Recent blocks with extras",
        description: "Retrieve the last 15 blocks with extended data including pool identification and fee statistics.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-blocks-v1)*",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-blocks-v1-from-height",
        method: "GET",
        path: "/api/v1/blocks/{height}",
        summary: "Blocks from height with extras",
        description: "Retrieve up to 15 blocks with extended data going backwards from the given height.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-blocks-v1)*",
        path_parameters: &[
            Parameter { api_name: "height", name: "height", required: true, value_name: "Height", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-cpfp",
        method: "GET",
        path: "/api/v1/cpfp/{txid}",
        summary: "CPFP info",
        description: "Returns ancestors and descendants for a CPFP (Child Pays For Parent) transaction, including the effective fee rate of the package.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-children-pay-for-parent)*",
        path_parameters: &[
            Parameter { api_name: "txid", name: "txid", required: true, value_name: "Txid", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-difficulty-adjustment",
        method: "GET",
        path: "/api/v1/difficulty-adjustment",
        summary: "Difficulty adjustment",
        description: "Get current difficulty adjustment progress and estimates.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-difficulty-adjustment)*",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-difficulty-adjustments",
        method: "GET",
        path: "/api/v1/mining/difficulty-adjustments",
        summary: "Difficulty adjustments (all time)",
        description: "Get historical difficulty adjustments including timestamp, block height, difficulty value, and percentage change.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-difficulty-adjustments)*",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-difficulty-adjustments-by-period",
        method: "GET",
        path: "/api/v1/mining/difficulty-adjustments/{time_period}",
        summary: "Difficulty adjustments",
        description: "Get historical difficulty adjustments for a time period. Valid periods: `24h`, `3d`, `1w`, `1m`, `3m`, `6m`, `1y`, `2y`, `3y`.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-difficulty-adjustments)*",
        path_parameters: &[
            Parameter { api_name: "time_period", name: "time-period", required: true, value_name: "TimePeriod", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-disk-usage",
        method: "GET",
        path: "/api/server/disk",
        summary: "Disk usage",
        description: "Returns the disk space used by BRK and Bitcoin data.",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-fullrbf-replacements",
        method: "GET",
        path: "/api/v1/fullrbf/replacements",
        summary: "Recent full-RBF replacements",
        description: "Same response shape as `GET /api/v1/replacements`, but limited to trees where at least one predecessor was non-signaling (full-RBF).\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-fullrbf-replacements)*",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-hashrate",
        method: "GET",
        path: "/api/v1/mining/hashrate",
        summary: "Network hashrate (all time)",
        description: "Get network hashrate and difficulty data for all time.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-hashrate)*",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-hashrate-by-period",
        method: "GET",
        path: "/api/v1/mining/hashrate/{time_period}",
        summary: "Network hashrate",
        description: "Get network hashrate and difficulty data for a time period. Valid periods: `24h`, `3d`, `1w`, `1m`, `3m`, `6m`, `1y`, `2y`, `3y`.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-hashrate)*",
        path_parameters: &[
            Parameter { api_name: "time_period", name: "time-period", required: true, value_name: "TimePeriod", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-health",
        method: "GET",
        path: "/health",
        summary: "Health check",
        description: "Liveness probe. Returns server identity, uptime, and indexed/computed heights from local state only (no bitcoind round-trip). For real chain-tip catch-up, request `GET /api/server/sync`.",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-historical-price",
        method: "GET",
        path: "/api/v1/historical-price",
        summary: "Historical price",
        description: "Get historical BTC/USD price. Optionally specify a UNIX timestamp to get the price at that time.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-historical-price)*",
        path_parameters: &[
        ],
        query_parameters: &[
            Parameter { api_name: "timestamp", name: "timestamp", required: false, value_name: "Timestamp", repeatable: false, description: None },
        ],
        request_body: None,
    },
    Command {
        name: "get-indexes",
        method: "GET",
        path: "/api/series/indexes",
        summary: "List available indexes",
        description: "Returns all available indexes with their accepted query aliases. Use any alias when querying series.",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-live-price",
        method: "GET",
        path: "/api/mempool/price",
        summary: "Live BTC/USD price",
        description: "Returns the current BTC/USD price in dollars, derived from on-chain round-dollar output patterns in the last 12 blocks plus mempool.",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-mempool",
        method: "GET",
        path: "/api/mempool",
        summary: "Mempool statistics",
        description: "Get current mempool statistics including transaction count, total vsize, total fees, and fee histogram.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-mempool)*",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-mempool-blocks",
        method: "GET",
        path: "/api/v1/fees/mempool-blocks",
        summary: "Projected mempool blocks",
        description: "Projected blocks for fee estimation. Block 0 reflects Bitcoin Core's actual next-block selection; blocks 1+ are a fee-tier approximation.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-mempool-blocks-fees)*",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-mempool-hash",
        method: "GET",
        path: "/api/mempool/hash",
        summary: "Mempool content hash",
        description: "Returns an opaque hash that changes whenever the projected next block changes. Same value as the mempool ETag. Useful as a freshness/liveness signal: if it stays constant for tens of seconds on a live network, the mempool sync loop has stalled.",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-mempool-recent",
        method: "GET",
        path: "/api/mempool/recent",
        summary: "Recent mempool transactions",
        description: "Get the last 10 transactions to enter the mempool.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-mempool-recent)*",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-mempool-txids",
        method: "GET",
        path: "/api/mempool/txids",
        summary: "Mempool transaction IDs",
        description: "Get all transaction IDs currently in the mempool.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-mempool-transaction-ids)*",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-openapi",
        method: "GET",
        path: "/openapi.json",
        summary: "OpenAPI specification",
        description: "Full OpenAPI 3.1 specification for this API.",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-oracle-histogram-outputs",
        method: "GET",
        path: "/api/oracle/histogram/outputs/{point}",
        summary: "Output value histogram at height or day",
        description: "Unfiltered output value histogram for a confirmed point. A block height (`840000`) gives every output in that block, coinbase included, binned by value on the oracle log scale; a calendar date (`YYYY-MM-DD`) sums every block that day. A flat array of log-scale bins.",
        path_parameters: &[
            Parameter { api_name: "point", name: "point", required: true, value_name: "string", repeatable: false, description: Some("Confirmed block height as decimal digits (`840000`) or calendar date in\n`YYYY-MM-DD` format.") },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-oracle-histogram-outputs-live",
        method: "GET",
        path: "/api/oracle/histogram/outputs/live",
        summary: "Live output value histogram",
        description: "Live unfiltered output value histogram for the forming mempool block. Every live output is binned by value on the oracle log scale; no oracle payment filters are applied. A flat array of log-scale bins, all zero when no mempool is configured.",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-oracle-histogram-payments",
        method: "GET",
        path: "/api/oracle/histogram/payments/{point}",
        summary: "Payment output histogram at height or day",
        description: "Smoothed histogram of oracle-eligible payment outputs for a confirmed point. A block height (`840000`) gives that block's oracle payment histogram; a calendar date (`YYYY-MM-DD`) gives the average of that day's per-block payment histograms. A flat array of log-scale bins.",
        path_parameters: &[
            Parameter { api_name: "point", name: "point", required: true, value_name: "string", repeatable: false, description: Some("Confirmed block height as decimal digits (`840000`) or calendar date in\n`YYYY-MM-DD` format.") },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-oracle-histogram-payments-live",
        method: "GET",
        path: "/api/oracle/histogram/payments/live",
        summary: "Live payment output histogram",
        description: "Live smoothed histogram of oracle-eligible payment outputs, binned by output value on the oracle log scale. It combines the committed oracle window with the forming mempool block. A flat array of log-scale bins.",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-oracle-price",
        method: "GET",
        path: "/api/oracle/price",
        summary: "Live BTC/USD price",
        description: "Current BTC/USD price in dollars. Same value as `GET /api/mempool/price`. Confirmed per-height history is available at `GET /api/series/price/height`.",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-pool",
        method: "GET",
        path: "/api/v1/mining/pool/{slug}",
        summary: "Mining pool details",
        description: "Get detailed information about a specific mining pool including block counts and shares for different time periods.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-mining-pool)*",
        path_parameters: &[
            Parameter { api_name: "slug", name: "slug", required: true, value_name: "PoolSlug", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-pool-blocks",
        method: "GET",
        path: "/api/v1/mining/pool/{slug}/blocks",
        summary: "Mining pool blocks",
        description: "Get the 10 most recent blocks mined by a specific pool.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-mining-pool-blocks)*",
        path_parameters: &[
            Parameter { api_name: "slug", name: "slug", required: true, value_name: "PoolSlug", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-pool-blocks-from",
        method: "GET",
        path: "/api/v1/mining/pool/{slug}/blocks/{height}",
        summary: "Mining pool blocks from height",
        description: "Get 10 blocks mined by a specific pool before (and including) the given height.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-mining-pool-blocks)*",
        path_parameters: &[
            Parameter { api_name: "slug", name: "slug", required: true, value_name: "PoolSlug", repeatable: false, description: None },
            Parameter { api_name: "height", name: "height", required: true, value_name: "Height", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-pool-hashrate",
        method: "GET",
        path: "/api/v1/mining/pool/{slug}/hashrate",
        summary: "Mining pool hashrate",
        description: "Get hashrate history for a specific mining pool.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-mining-pool-hashrate)*",
        path_parameters: &[
            Parameter { api_name: "slug", name: "slug", required: true, value_name: "PoolSlug", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-pool-stats",
        method: "GET",
        path: "/api/v1/mining/pools/{time_period}",
        summary: "Mining pool statistics",
        description: "Get mining pool statistics for a time period. Valid periods: `24h`, `3d`, `1w`, `1m`, `3m`, `6m`, `1y`, `2y`, `3y`.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-mining-pools)*",
        path_parameters: &[
            Parameter { api_name: "time_period", name: "time-period", required: true, value_name: "TimePeriod", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-pools",
        method: "GET",
        path: "/api/v1/mining/pools",
        summary: "List all mining pools",
        description: "Get list of all known mining pools with their identifiers.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-mining-pools)*",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-pools-hashrate",
        method: "GET",
        path: "/api/v1/mining/hashrate/pools",
        summary: "All pools hashrate (all time)",
        description: "Get hashrate data for all mining pools.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-mining-pool-hashrates)*",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-pools-hashrate-by-period",
        method: "GET",
        path: "/api/v1/mining/hashrate/pools/{time_period}",
        summary: "All pools hashrate",
        description: "Get hashrate data for all mining pools for a time period. Valid periods: `1m`, `3m`, `6m`, `1y`, `2y`, `3y`.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-mining-pool-hashrates)*",
        path_parameters: &[
            Parameter { api_name: "time_period", name: "time-period", required: true, value_name: "TimePeriod", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-precise-fees",
        method: "GET",
        path: "/api/v1/fees/precise",
        summary: "Recommended fee rates (precise)",
        description: "Recommended fee rates by confirmation target, with up to three decimal places and support for sub-sat/vB rates.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-recommended-fees-precise)*",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-prices",
        method: "GET",
        path: "/api/v1/prices",
        summary: "Current BTC price",
        description: "Returns bitcoin latest price (on-chain derived, USD only).\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-price)*",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-recommended-fees",
        method: "GET",
        path: "/api/v1/fees/recommended",
        summary: "Recommended fees",
        description: "Recommended fee rates by confirmation target.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-recommended-fees)*",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-replacements",
        method: "GET",
        path: "/api/v1/replacements",
        summary: "Recent RBF replacements",
        description: "Returns up to 25 most-recent RBF replacement trees across the whole mempool. Each entry has the same shape as `tx_rbf().replacements`.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-replacements)*",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-reward-stats",
        method: "GET",
        path: "/api/v1/mining/reward-stats/{block_count}",
        summary: "Mining reward statistics",
        description: "Get mining reward statistics for the last N blocks including total rewards, fees, and transaction count.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-reward-stats)*",
        path_parameters: &[
            Parameter { api_name: "block_count", name: "block-count", required: true, value_name: "integer", repeatable: false, description: Some("Number of recent blocks to include") },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-series",
        method: "GET",
        path: "/api/series/{series}/{index}",
        summary: "Get series data",
        description: "Fetch data for a specific series at the given index. Use query parameters to filter by date range and format (json/csv).",
        path_parameters: &[
            Parameter { api_name: "series", name: "series", required: true, value_name: "SeriesName", repeatable: false, description: Some("Series name") },
            Parameter { api_name: "index", name: "index", required: true, value_name: "Index", repeatable: false, description: Some("Aggregation index") },
        ],
        query_parameters: &[
            Parameter { api_name: "start", name: "start", required: false, value_name: "RangeIndex", repeatable: false, description: Some("Inclusive start: integer index, date (YYYY-MM-DD), or timestamp (ISO 8601). Negative integers count from end. Aliases: `from`, `f`, `s`") },
            Parameter { api_name: "end", name: "end", required: false, value_name: "RangeIndex", repeatable: false, description: Some("Exclusive end: integer index, date (YYYY-MM-DD), or timestamp (ISO 8601). Negative integers count from end. Aliases: `to`, `t`, `e`") },
            Parameter { api_name: "limit", name: "limit", required: false, value_name: "Limit", repeatable: false, description: Some("Maximum number of values to return (ignored if `end` is set). Aliases: `count`, `c`, `l`") },
            Parameter { api_name: "format", name: "format", required: false, value_name: "Format", repeatable: false, description: Some("Format of the output") },
        ],
        request_body: None,
    },
    Command {
        name: "get-series-bulk",
        method: "GET",
        path: "/api/series/bulk",
        summary: "Bulk series data",
        description: "Fetch multiple series in a single request. Supports filtering by index and date range. Returns an array of SeriesData objects. For a single series, use `get_series` instead.",
        path_parameters: &[
        ],
        query_parameters: &[
            Parameter { api_name: "series", name: "series", required: true, value_name: "SeriesList", repeatable: false, description: Some("Requested series") },
            Parameter { api_name: "index", name: "index", required: true, value_name: "Index", repeatable: false, description: Some("Index to query") },
            Parameter { api_name: "start", name: "start", required: false, value_name: "RangeIndex", repeatable: false, description: Some("Inclusive start: integer index, date (YYYY-MM-DD), or timestamp (ISO 8601). Negative integers count from end. Aliases: `from`, `f`, `s`") },
            Parameter { api_name: "end", name: "end", required: false, value_name: "RangeIndex", repeatable: false, description: Some("Exclusive end: integer index, date (YYYY-MM-DD), or timestamp (ISO 8601). Negative integers count from end. Aliases: `to`, `t`, `e`") },
            Parameter { api_name: "limit", name: "limit", required: false, value_name: "Limit", repeatable: false, description: Some("Maximum number of values to return (ignored if `end` is set). Aliases: `count`, `c`, `l`") },
            Parameter { api_name: "format", name: "format", required: false, value_name: "Format", repeatable: false, description: Some("Format of the output") },
        ],
        request_body: None,
    },
    Command {
        name: "get-series-count",
        method: "GET",
        path: "/api/series/count",
        summary: "Series count",
        description: "Returns the number of series available per index type.",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-series-data",
        method: "GET",
        path: "/api/series/{series}/{index}/data",
        summary: "Get raw series data",
        description: "Returns just the data array without the SeriesData wrapper. Supports the same range and format parameters as `GET /api/series/{series}/{index}`.",
        path_parameters: &[
            Parameter { api_name: "series", name: "series", required: true, value_name: "SeriesName", repeatable: false, description: Some("Series name") },
            Parameter { api_name: "index", name: "index", required: true, value_name: "Index", repeatable: false, description: Some("Aggregation index") },
        ],
        query_parameters: &[
            Parameter { api_name: "start", name: "start", required: false, value_name: "RangeIndex", repeatable: false, description: Some("Inclusive start: integer index, date (YYYY-MM-DD), or timestamp (ISO 8601). Negative integers count from end. Aliases: `from`, `f`, `s`") },
            Parameter { api_name: "end", name: "end", required: false, value_name: "RangeIndex", repeatable: false, description: Some("Exclusive end: integer index, date (YYYY-MM-DD), or timestamp (ISO 8601). Negative integers count from end. Aliases: `to`, `t`, `e`") },
            Parameter { api_name: "limit", name: "limit", required: false, value_name: "Limit", repeatable: false, description: Some("Maximum number of values to return (ignored if `end` is set). Aliases: `count`, `c`, `l`") },
            Parameter { api_name: "format", name: "format", required: false, value_name: "Format", repeatable: false, description: Some("Format of the output") },
        ],
        request_body: None,
    },
    Command {
        name: "get-series-info",
        method: "GET",
        path: "/api/series/{series}",
        summary: "Get series info",
        description: "Returns the optional description, supported indexes, and value type for the specified series.",
        path_parameters: &[
            Parameter { api_name: "series", name: "series", required: true, value_name: "SeriesName", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-series-latest",
        method: "GET",
        path: "/api/series/{series}/{index}/latest",
        summary: "Get latest series value",
        description: "Returns the single most recent value for a series, unwrapped (not inside a SeriesData object).",
        path_parameters: &[
            Parameter { api_name: "series", name: "series", required: true, value_name: "SeriesName", repeatable: false, description: Some("Series name") },
            Parameter { api_name: "index", name: "index", required: true, value_name: "Index", repeatable: false, description: Some("Aggregation index") },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-series-len",
        method: "GET",
        path: "/api/series/{series}/{index}/len",
        summary: "Get series data length",
        description: "Returns the total number of data points for a series at the given index.",
        path_parameters: &[
            Parameter { api_name: "series", name: "series", required: true, value_name: "SeriesName", repeatable: false, description: Some("Series name") },
            Parameter { api_name: "index", name: "index", required: true, value_name: "Index", repeatable: false, description: Some("Aggregation index") },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-series-tree",
        method: "GET",
        path: "/api/series",
        summary: "Series catalog",
        description: "Returns the complete hierarchical catalog of available series organized as a tree structure. Series are grouped by categories and subcategories.",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-series-version",
        method: "GET",
        path: "/api/series/{series}/{index}/version",
        summary: "Get series version",
        description: "Returns the current version of a series. Changes when the series data is updated.",
        path_parameters: &[
            Parameter { api_name: "series", name: "series", required: true, value_name: "SeriesName", repeatable: false, description: Some("Series name") },
            Parameter { api_name: "index", name: "index", required: true, value_name: "Index", repeatable: false, description: Some("Aggregation index") },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-sync-status",
        method: "GET",
        path: "/api/server/sync",
        summary: "Sync status",
        description: "Returns the sync status of the indexer, including indexed height, tip height, blocks behind, and last indexed timestamp.",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-transaction-times",
        method: "GET",
        path: "/api/v1/transaction-times",
        summary: "Transaction first-seen times",
        description: "Returns timestamps when transactions were first seen in the mempool. Returns 0 for mined or unknown transactions.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-transaction-times)*",
        path_parameters: &[
        ],
        query_parameters: &[
            Parameter { api_name: "txId[]", name: "tx-id", required: true, value_name: "Txid[]", repeatable: true, description: Some("Transaction IDs to look up (max 250 per request).") },
        ],
        request_body: None,
    },
    Command {
        name: "get-tx",
        method: "GET",
        path: "/api/tx/{txid}",
        summary: "Transaction information",
        description: "Retrieve complete transaction data by transaction ID (txid). Returns inputs, outputs, fee, size, and confirmation status.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-transaction)*",
        path_parameters: &[
            Parameter { api_name: "txid", name: "txid", required: true, value_name: "Txid", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-tx-by-index",
        method: "GET",
        path: "/api/tx-index/{index}",
        summary: "Txid by index",
        description: "Retrieve the transaction ID (txid) at a given global transaction index. Returns the txid as plain text.",
        path_parameters: &[
            Parameter { api_name: "index", name: "index", required: true, value_name: "TxIndex", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-tx-hex",
        method: "GET",
        path: "/api/tx/{txid}/hex",
        summary: "Transaction hex",
        description: "Retrieve the raw transaction as a hex-encoded string. Returns the serialized transaction in hexadecimal format.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-transaction-hex)*",
        path_parameters: &[
            Parameter { api_name: "txid", name: "txid", required: true, value_name: "Txid", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-tx-merkle-proof",
        method: "GET",
        path: "/api/tx/{txid}/merkle-proof",
        summary: "Transaction merkle proof",
        description: "Get the merkle inclusion proof for a transaction.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-transaction-merkle-proof)*",
        path_parameters: &[
            Parameter { api_name: "txid", name: "txid", required: true, value_name: "Txid", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-tx-merkleblock-proof",
        method: "GET",
        path: "/api/tx/{txid}/merkleblock-proof",
        summary: "Transaction merkleblock proof",
        description: "Get the merkleblock proof for a transaction (BIP37 format, hex encoded).\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-transaction-merkleblock-proof)*",
        path_parameters: &[
            Parameter { api_name: "txid", name: "txid", required: true, value_name: "Txid", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-tx-outspend",
        method: "GET",
        path: "/api/tx/{txid}/outspend/{vout}",
        summary: "Output spend status",
        description: "Get the spending status of a transaction output. Returns whether the output has been spent and, if so, the spending transaction details.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-transaction-outspend)*",
        path_parameters: &[
            Parameter { api_name: "txid", name: "txid", required: true, value_name: "Txid", repeatable: false, description: Some("Transaction ID") },
            Parameter { api_name: "vout", name: "vout", required: true, value_name: "Vout", repeatable: false, description: Some("Output index") },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-tx-outspends",
        method: "GET",
        path: "/api/tx/{txid}/outspends",
        summary: "All output spend statuses",
        description: "Get the spending status of all outputs in a transaction. Returns an array with the spend status for each output.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-transaction-outspends)*",
        path_parameters: &[
            Parameter { api_name: "txid", name: "txid", required: true, value_name: "Txid", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-tx-raw",
        method: "GET",
        path: "/api/tx/{txid}/raw",
        summary: "Transaction raw",
        description: "Returns a transaction as binary data.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-transaction-raw)*",
        path_parameters: &[
            Parameter { api_name: "txid", name: "txid", required: true, value_name: "Txid", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-tx-rbf",
        method: "GET",
        path: "/api/v1/tx/{txid}/rbf",
        summary: "RBF replacement history",
        description: "Returns the RBF replacement tree for a transaction, if any. Both `replacements` and `replaces` are null when the tx has no known RBF history within the mempool monitor's retention window.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-transaction-rbf-history)*",
        path_parameters: &[
            Parameter { api_name: "txid", name: "txid", required: true, value_name: "Txid", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-tx-status",
        method: "GET",
        path: "/api/tx/{txid}/status",
        summary: "Transaction status",
        description: "Retrieve the confirmation status of a transaction. Returns whether the transaction is confirmed and, if so, the block height, hash, and timestamp.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-transaction-status)*",
        path_parameters: &[
            Parameter { api_name: "txid", name: "txid", required: true, value_name: "Txid", repeatable: false, description: None },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "get-urpd",
        method: "GET",
        path: "/api/urpd/{cohort}",
        summary: "Latest URPD",
        description: "URPD for the most recent available date in the cohort. The response's `date` field echoes which date was served. Returns `{ cohort, date, weight, aggregation, close, total_supply, buckets }`. `close` and each bucket's `price_floor`, `realized_cap`, and `unrealized_pnl` are USD; `total_supply` and bucket `supply` are BTC. `unrealized_pnl` can be negative.",
        path_parameters: &[
            Parameter { api_name: "cohort", name: "cohort", required: true, value_name: "Cohort", repeatable: false, description: None },
        ],
        query_parameters: &[
            Parameter { api_name: "agg", name: "agg", required: false, value_name: "UrpdAggregation", repeatable: false, description: Some("Aggregation strategy. Default: raw (no aggregation). Accepts `bucket` as alias.") },
            Parameter { api_name: "weight", name: "weight", required: false, value_name: "UrpdWeight", repeatable: false, description: Some("Supply weighting. Default: raw (unweighted).") },
        ],
        request_body: None,
    },
    Command {
        name: "get-urpd-at",
        method: "GET",
        path: "/api/urpd/{cohort}/{date}",
        summary: "URPD at date",
        description: "URPD for a (cohort, date) pair. Returns `{ cohort, date, weight, aggregation, close, total_supply, buckets }` where each bucket is `{ price_floor, supply, realized_cap, unrealized_pnl }`. `close`, `price_floor`, `realized_cap`, and `unrealized_pnl` are USD; `total_supply` and `supply` are BTC. `unrealized_pnl` can be negative.",
        path_parameters: &[
            Parameter { api_name: "cohort", name: "cohort", required: true, value_name: "Cohort", repeatable: false, description: None },
            Parameter { api_name: "date", name: "date", required: true, value_name: "string", repeatable: false, description: Some("Calendar date of the URPD snapshot in `YYYY-MM-DD` format.") },
        ],
        query_parameters: &[
            Parameter { api_name: "agg", name: "agg", required: false, value_name: "UrpdAggregation", repeatable: false, description: Some("Aggregation strategy. Default: raw (no aggregation). Accepts `bucket` as alias.") },
            Parameter { api_name: "weight", name: "weight", required: false, value_name: "UrpdWeight", repeatable: false, description: Some("Supply weighting. Default: raw (unweighted).") },
        ],
        request_body: None,
    },
    Command {
        name: "get-version",
        method: "GET",
        path: "/version",
        summary: "API version",
        description: "Returns the current version of the API server",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "list-series",
        method: "GET",
        path: "/api/series/list",
        summary: "Series list",
        description: "Paginated flat list of all available series names. Use `page` query param for pagination.",
        path_parameters: &[
        ],
        query_parameters: &[
            Parameter { api_name: "page", name: "page", required: false, value_name: "integer", repeatable: false, description: Some("Pagination index") },
            Parameter { api_name: "per_page", name: "per-page", required: false, value_name: "integer", repeatable: false, description: Some("Results per page (default: 1000, max: 1000)") },
        ],
        request_body: None,
    },
    Command {
        name: "list-urpd-cohorts",
        method: "GET",
        path: "/api/urpd",
        summary: "Available URPD cohorts",
        description: "Cohorts for which URPD data is available. Returns names like `all`, `sth`, `lth`, `utxos_under_1h_old`.",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
    Command {
        name: "list-urpd-dates",
        method: "GET",
        path: "/api/urpd/{cohort}/dates",
        summary: "Available URPD dates",
        description: "Dates for which a URPD snapshot is available for the cohort and selected `weight`. One entry per UTC day, sorted ascending.",
        path_parameters: &[
            Parameter { api_name: "cohort", name: "cohort", required: true, value_name: "Cohort", repeatable: false, description: None },
        ],
        query_parameters: &[
            Parameter { api_name: "weight", name: "weight", required: false, value_name: "UrpdWeight", repeatable: false, description: Some("Supply weighting. Default: raw (unweighted).") },
        ],
        request_body: None,
    },
    Command {
        name: "post-tx",
        method: "POST",
        path: "/api/tx",
        summary: "Broadcast transaction",
        description: "Broadcast a raw transaction to the network. The transaction should be provided as hex in the request body. The txid will be returned on success.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#post-transaction)*",
        path_parameters: &[
        ],
        query_parameters: &[
        ],
        request_body: Some(RequestBody { value_name: "string", required: true, content_type: "text/plain; charset=utf-8" }),
    },
    Command {
        name: "search-series",
        method: "GET",
        path: "/api/series/search",
        summary: "Search series",
        description: "Search series by name or descriptive terms. Matches metric names, descriptions, formulas, cohort aliases, partial words, and common typos.",
        path_parameters: &[
        ],
        query_parameters: &[
            Parameter { api_name: "q", name: "q", required: true, value_name: "SeriesName", repeatable: false, description: Some("Search query string") },
            Parameter { api_name: "limit", name: "limit", required: false, value_name: "Limit", repeatable: false, description: Some("Maximum number of results") },
        ],
        request_body: None,
    },
    Command {
        name: "validate-address",
        method: "GET",
        path: "/api/v1/validate-address/{address}",
        summary: "Validate address",
        description: "Validate a Bitcoin address and get information about its type and scriptPubKey. Returns `isvalid: false` with an error message for invalid addresses.\n\n*[Mempool.space docs](https://mempool.space/docs/api/rest#get-address-validate)*",
        path_parameters: &[
            Parameter { api_name: "address", name: "address", required: true, value_name: "string", repeatable: false, description: Some("Bitcoin address to validate (can be any string)") },
        ],
        query_parameters: &[
        ],
        request_body: None,
    },
];
