[package]
name = "brk_logger"
description = "A thin wrapper around tracing with daily, per-level log files"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
jiff = { workspace = true }
owo-colors = { workspace = true }
tracing = { workspace = true }
tracing-log = "0.2"
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt", "std"] }
