[package]
name = "bitview_traversable"
description = "Traits for Vecs structs throughout Bitview"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[features]
derive = ["bitview_traversable_derive"]
pco = ["vecdb/pco"]
zerocopy = ["vecdb/zerocopy"]
lz4 = ["vecdb/lz4"]
zstd = ["vecdb/zstd"]

[dependencies]
bitview_traversable_derive = { workspace = true, optional = true }
bitview_types = { workspace = true }
brk_types = { workspace = true }
indexmap = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
vecdb = { workspace = true }

[dev-dependencies]
bitview_traversable_derive = { workspace = true }
serde_json = { workspace = true }
