[package]
name = "brk_cli"
description = "A command line interface to run a BRK instance"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
anyhow = "1.0"
bitview = { workspace = true }

[[bin]]
name = "brk"
path = "src/main.rs"
