[package]
name = "bitview_plugin_capital_sentiment"
description = "The capital sentiment model plugin for Bitview"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage = "https://bitview.dev"
repository.workspace = true

[dependencies]
bitview_compute = { workspace = true }
bitview_plugin = { workspace = true }
bitview_plugin_distribution = { workspace = true }
bitview_plugin_indexes = { workspace = true }
bitview_plugin_market = { workspace = true }
bitview_plugin_price = { workspace = true }
brk_error = { workspace = true, features = ["vecdb"] }
brk_indexer = { workspace = true }
bitview_traversable = { workspace = true }
brk_types = { workspace = true }
vecdb = { workspace = true }
