[package]
name = "brk_fetcher"
description = "A Bitcoin price fetcher"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude = ["examples/"]

[dependencies]
brk_error = { workspace = true, features = ["ureq", "serde_json"] }
brk_types = { workspace = true }
tracing = { workspace = true }
ureq = { workspace = true }
serde_json = { workspace = true }
