[package]
name = "brk"
description.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
version.workspace = true

[features]
full = [
    "error",
    "fetcher",
    "iterator",
    "logger",
    "mempool",
    "oracle",
    "reader",
    "rpc",
    "store",
    "types",
]
error = ["brk_error"]
fetcher = ["brk_fetcher"]
iterator = ["brk_iterator"]
logger = ["brk_logger"]
mempool = ["brk_mempool"]
oracle = ["brk_oracle"]
reader = ["brk_reader"]
rpc = ["brk_rpc"]
store = ["brk_store"]
types = ["brk_types"]

[dependencies]
brk_error = { workspace = true, optional = true }
brk_fetcher = { workspace = true, optional = true }
brk_iterator = { workspace = true, optional = true }
brk_logger = { workspace = true, optional = true }
brk_mempool = { workspace = true, optional = true }
brk_oracle = { workspace = true, optional = true }
brk_reader = { workspace = true, optional = true }
brk_rpc = { workspace = true, optional = true }
brk_store = { workspace = true, optional = true }
brk_types = { workspace = true, optional = true }

[package.metadata.docs.rs]
all-features = true
