[package]
name = "bitview_plugin_pools"
description = "The mining pools plugin for Bitview"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage = "https://bitview.dev"
repository.workspace = true

[dependencies]
bitview_compute = { workspace = true }
bitview_plugin = { workspace = true }
bitview_plugin_indexes = { workspace = true }
bitview_plugin_mining = { workspace = true }
bitview_plugin_price = { workspace = true }
brk_error = { workspace = true, features = ["vecdb"] }
bitview_plugin_indexer = { workspace = true }
bitview_traversable = { workspace = true }
brk_types = { workspace = true }
derive_more = { workspace = true }
parking_lot = { workspace = true }
rayon = { workspace = true }
rustc-hash = { workspace = true }
tracing = { workspace = true }
vecdb = { workspace = true }
