[package]
name = "bitview_traversable_derive"
description = "Derive macro for bitview_traversable"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
syn = "3.0"
quote = "1.0"
proc-macro2 = "1.0.107"
