[package]
name = "brk_fjall"
description = "BRK-maintained fork of Fjall, an embeddable log-structured key-value storage engine"
license.workspace = true
version.workspace = true
edition.workspace = true
readme = "README.md"
repository.workspace = true
homepage.workspace = true

[lib]
name = "fjall"
path = "src/lib.rs"

[dependencies]
lsm-tree = { workspace = true }
log = { workspace = true }
flume = { version = "0.12.0", default-features = false }

[dev-dependencies]
tempfile = { workspace = true }
