[package]
name = "statedb"
description = "Snapshot and diff storage for UTXO state aggregated by creation height"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pco = { workspace = true }
zerocopy = { version = "0.8.58", features = ["derive"] }

[dev-dependencies]
tempfile = { workspace = true }
