[package]
name = "brk_oracle"
description = "Pure on-chain BTC/USD price oracle algorithm"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
brk_types = { workspace = true }
derive_more = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
