[package]
name = "bitview_bencher_visualizer"
description = "A generator of charts for bitview_bencher"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false

[dependencies]
derive_more = { workspace = true }
plotters = "0.3.7"
