[package]
name = "brk_rpc"
description = "A thin wrapper around Bitcoin Core's JSON-RPC"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude = ["examples/"]

[features]
async = ["dep:base64", "dep:http-body-util", "dep:hyper", "dep:hyper-util", "dep:tokio"]

[dependencies]
base64 = { version = "0.23", optional = true }
http-body-util = { version = "0.1", optional = true }
hyper = { version = "1", features = ["client", "http1"], optional = true }
hyper-util = { version = "0.1", features = ["tokio"], optional = true }
tokio = { workspace = true, features = ["fs", "time", "net", "sync", "macros"], optional = true }
bitcoin = { workspace = true }
brk_error = { workspace = true, features = ["corepc", "serde_json"] }
brk_types = { workspace = true }
corepc-jsonrpc = { workspace = true }
corepc-types = { workspace = true }
parking_lot = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
