use std::collections::{BTreeMap, BTreeSet};

use aide::axum::ApiRouter;
use bitview_bindgen::client_paths;
use bitview_catalog::{TreeNode, extract_json_type};
use bitview_query::Vecs;
use bitview_server::{ApiRoutes, finish_openapi};
use brk_error::Result;

use crate::{AllPlugins, Snapshot};

/// The series tree as clients see it: one line per leaf (with a schema id), the typed path of
/// every leaf in each generated client, descriptions, value schemas, and the OpenAPI document.
pub fn render_api(plugins: &AllPlugins) -> Result<Vec<Snapshot>> {
    let defaults = Vecs::build(&plugins.defaults);
    let all = Vecs::build(plugins);

    let mut leaves = Leaves::default();
    let default_lines = leaves.lines(defaults.catalog());
    let all_lines = leaves.lines(all.catalog());
    let default_set = default_lines.iter().collect::<BTreeSet<_>>();
    let all_set = all_lines.iter().collect::<BTreeSet<_>>();

    let mut out =
        String::from("# Generated by `cargo api` (crates/bitview_devtools). Do not edit.\n");
    section(
        &mut out,
        "Default composition (generated clients): path, series, value type, JSON type, schema, indexes",
        default_lines.iter(),
    );
    section(
        &mut out,
        "Added by optional plugins",
        all_lines.iter().filter(|line| !default_set.contains(line)),
    );
    section(
        &mut out,
        "Default lines missing from the full composition",
        default_lines.iter().filter(|line| !all_set.contains(line)),
    );
    section(
        &mut out,
        "Typed client paths (default composition): series, Rust, JavaScript, Python",
        client_paths(defaults.catalog()).into_iter().map(|path| {
            format!(
                "{}\t{}\t{}\t{}",
                path.series, path.rust, path.javascript, path.python
            )
        }),
    );
    section(
        &mut out,
        "Descriptions",
        leaves
            .descriptions
            .iter()
            .map(|(series, description)| format!("{series}\t{description}")),
    );
    section(
        &mut out,
        "Value schemas: id, schema",
        leaves
            .schemas
            .iter()
            .map(|(id, schema)| format!("{id}\t{schema}")),
    );

    let (_, openapi) = finish_openapi(ApiRouter::new().add_api_routes());
    let mut openapi = serde_json::to_string_pretty(&openapi)?;
    openapi.push('\n');

    Ok(vec![
        Snapshot {
            file: "api.txt",
            contents: out,
        },
        Snapshot {
            file: "openapi.json",
            contents: openapi,
        },
    ])
}

fn section(out: &mut String, title: &str, lines: impl Iterator<Item = impl AsRef<str>>) {
    out.push_str(&format!("\n## {title}\n"));
    for line in lines {
        out.push_str(line.as_ref());
        out.push('\n');
    }
}

#[derive(Default)]
struct Leaves {
    descriptions: BTreeMap<String, String>,
    schemas: BTreeMap<String, String>,
}

impl Leaves {
    fn lines(&mut self, catalog: &TreeNode) -> Vec<String> {
        let mut lines = Vec::new();
        self.walk(catalog, &mut String::new(), &mut lines);
        lines
    }

    fn walk(&mut self, node: &TreeNode, path: &mut String, lines: &mut Vec<String>) {
        match node {
            TreeNode::Branch(branch) if branch.is_empty() => {
                lines.push(format!("{path}\t(empty branch)"));
            }
            TreeNode::Branch(branch) => {
                for (key, child) in branch.iter() {
                    let len = path.len();
                    if !path.is_empty() {
                        path.push('.');
                    }
                    path.push_str(key);
                    self.walk(child, path, lines);
                    path.truncate(len);
                }
            }
            TreeNode::Leaf(leaf) => {
                let schema = leaf.schema.to_string();
                let schema_id = fnv1a(&schema);
                let indexes = leaf
                    .indexes()
                    .iter()
                    .map(ToString::to_string)
                    .collect::<Vec<_>>()
                    .join(",");
                lines.push(format!(
                    "{path}\t{}\t{}\t{}\t{schema_id}\t{indexes}",
                    leaf.name(),
                    leaf.kind(),
                    extract_json_type(&leaf.schema),
                ));
                if let Some(description) = &leaf.leaf.description {
                    self.descriptions
                        .insert(leaf.name().to_owned(), description.to_string());
                }
                self.schemas.insert(schema_id, schema);
            }
        }
    }
}

/// Stable short id for a schema (FNV-1a, 64 bits).
fn fnv1a(text: &str) -> String {
    let hash = text.bytes().fold(0xcbf29ce484222325_u64, |hash, byte| {
        (hash ^ u64::from(byte)).wrapping_mul(0x100000001b3)
    });
    format!("{hash:016x}")
}
