use std::{
    collections::{BTreeMap, BTreeSet},
    io,
};

use aide::axum::ApiRouter;
use bitview_bindgen::client_paths;
use bitview_catalog::{TreeNode, extract_json_type};
use bitview_query::Vecs;
use bitview_server::{ApiRoutes, finish_openapi};
use brk_error::{Error, Result};

use crate::{AllPlugins, Snapshot, errors::render_errors};

/// The series tree as clients see it: one line per leaf (with a schema id), descriptions and
/// value schemas; the typed path of every leaf in each generated client; the OpenAPI document;
/// the HTTP response of every error scenario (G8).
pub fn render_api(plugins: &AllPlugins) -> Result<Vec<Snapshot>> {
    let defaults = Vecs::build(&plugins.defaults);
    let all = Vecs::build(plugins);
    check_value_types(&all)?;
    let mut leaves = Leaves::default();
    let default_lines = leaves.lines(defaults.catalog());
    let all_lines = leaves.lines(all.catalog());
    let default_set = default_lines.iter().collect::<BTreeSet<_>>();
    let all_set = all_lines.iter().collect::<BTreeSet<_>>();

    let mut out =
        String::from("# Generated by `cargo api` (crates/bitview_devtools). Do not edit.\n");
    section(
        &mut out,
        "Default composition (generated clients): path, series, value type, JSON type, schema, indexes, nullable indexes (all: every index)",
        default_lines.iter(),
    );
    section(
        &mut out,
        "Added by optional plugins",
        all_lines.iter().filter(|line| !default_set.contains(line)),
    );
    section(
        &mut out,
        "Default lines missing from the full composition",
        default_lines.iter().filter(|line| !all_set.contains(line)),
    );
    section(
        &mut out,
        "Ids published by several plugins (full composition): id, serving plugin, others (= matching)",
        all.shared_series().iter().map(|shared| {
            let also = shared
                .also
                .iter()
                .map(|(plugin, matches)| format!("{plugin}{}", if *matches { "=" } else { "!" }))
                .collect::<Vec<_>>()
                .join(",");
            format!("{}\t{}\t{also}", shared.name, shared.served_by)
        }),
    );
    section(
        &mut out,
        "Descriptions",
        leaves
            .descriptions
            .iter()
            .map(|(series, description)| format!("{series}\t{description}")),
    );
    section(
        &mut out,
        "Value schemas: id, schema",
        leaves
            .schemas
            .iter()
            .map(|(id, schema)| format!("{id}\t{schema}")),
    );

    let (_, openapi) = finish_openapi(ApiRouter::new().add_api_routes());
    let mut openapi = serde_json::to_string_pretty(&openapi)?;
    openapi.push('\n');

    // Read by scripts/check_client_paths.{mjs,py}, which walk each path in the generated clients.
    let mut paths =
        String::from("# series\trust\tjavascript\tpython\tindexes (default composition)\n");
    for path in client_paths(defaults.catalog()) {
        let indexes = path
            .indexes
            .iter()
            .map(|index| {
                serde_json::to_value(index)
                    .map(|value| value.as_str().unwrap_or_default().to_owned())
            })
            .collect::<serde_json::Result<Vec<_>>>()?
            .join(",");
        paths.push_str(&format!(
            "{}\t{}\t{}\t{}\t{indexes}\n",
            path.series, path.rust, path.javascript, path.python
        ));
    }

    Ok(vec![
        Snapshot {
            file: "api.txt",
            contents: out,
        },
        Snapshot {
            file: "client-paths.tsv",
            contents: paths,
        },
        Snapshot {
            file: "openapi.json",
            contents: openapi,
        },
        render_errors(plugins)?,
    ])
}

fn section(out: &mut String, title: &str, lines: impl Iterator<Item = impl AsRef<str>>) {
    out.push_str(&format!("\n## {title}\n"));
    for line in lines {
        out.push_str(line.as_ref());
        out.push('\n');
    }
}

/// Fails when an id is published with more than one value type: a duplicate at the same index
/// loses its path, and one at other indexes would give the id two types. Open compositions only
/// report it; in our own, it is a bug.
fn check_value_types(all: &Vecs) -> Result<()> {
    let ids = all
        .shared_series()
        .iter()
        .filter(|shared| shared.also.iter().any(|(_, matches)| !matches))
        .map(|shared| shared.name.as_str())
        .chain(all.value_type_conflicts().iter().copied())
        .collect::<BTreeSet<_>>();
    if ids.is_empty() {
        return Ok(());
    }
    Err(Error::from(io::Error::other(format!(
        "ids published with different value types: {}",
        ids.into_iter().collect::<Vec<_>>().join(", ")
    ))))
}

#[derive(Default)]
struct Leaves {
    descriptions: BTreeMap<String, String>,
    schemas: BTreeMap<String, String>,
}

impl Leaves {
    fn lines(&mut self, catalog: &TreeNode) -> Vec<String> {
        let mut lines = Vec::new();
        self.walk(catalog, &mut String::new(), &mut lines);
        lines
    }

    fn walk(&mut self, node: &TreeNode, path: &mut String, lines: &mut Vec<String>) {
        match node {
            TreeNode::Branch(branch) if branch.is_empty() => {
                lines.push(format!("{path}\t(empty branch)"));
            }
            TreeNode::Branch(branch) => {
                for (key, child) in branch.iter() {
                    let len = path.len();
                    if !path.is_empty() {
                        path.push('.');
                    }
                    path.push_str(key);
                    self.walk(child, path, lines);
                    path.truncate(len);
                }
            }
            TreeNode::Leaf(leaf) => {
                let schema = leaf.schema.to_string();
                let schema_id = fnv1a(&schema);
                let indexes = leaf
                    .indexes()
                    .iter()
                    .map(ToString::to_string)
                    .collect::<Vec<_>>()
                    .join(",");
                let nullable = if leaf.nullable() == leaf.indexes() {
                    "all".to_owned()
                } else {
                    leaf.nullable()
                        .iter()
                        .map(ToString::to_string)
                        .collect::<Vec<_>>()
                        .join(",")
                };
                lines.push(format!(
                    "{path}\t{}\t{}\t{}\t{schema_id}\t{indexes}\t{nullable}",
                    leaf.name(),
                    leaf.kind(),
                    extract_json_type(&leaf.schema),
                ));
                if let Some(description) = &leaf.leaf.description {
                    self.descriptions
                        .insert(leaf.name().to_owned(), description.to_string());
                }
                self.schemas.insert(schema_id, schema);
            }
        }
    }
}

/// Stable short id for a schema (FNV-1a, 64 bits).
fn fnv1a(text: &str) -> String {
    let hash = text.bytes().fold(0xcbf29ce484222325_u64, |hash, byte| {
        (hash ^ u64::from(byte)).wrapping_mul(0x100000001b3)
    });
    format!("{hash:016x}")
}
