use std::{
    io,
    net::{IpAddr, Ipv4Addr},
    path::PathBuf,
};

use axum::{
    body::{Body, to_bytes},
    http::{Method, Request, Response},
    response::IntoResponse,
};
use bitview_query::AsyncQuery;
use bitview_server::{
    CdnCacheMode, DEFAULT_MAX_UTXOS, DEFAULT_MAX_WEIGHT, Error as ServerError, Port, ServerConfig,
    Website, app,
};
use brk_error::{Error, Result};
use tempfile::tempdir;
use tokio::runtime::Builder;
use tower::ServiceExt;

use crate::{AllPlugins, Snapshot};

const HASH: &str = "000000000000000000000000000000000000000000000000000000000000dead";
const ADDRESS: &str = "bc1qar0srrr7xfkvy5l643lydnw9re59gtzzwf5mdq";

/// G8: the HTTP response of every client-visible error scenario (status, headers, body).
///
/// Requests go through the real application (`bitview_server::app`: routes, rejections, the
/// JSON error rewrite, POST no-store, CORS) over the offline import, with no mempool and an
/// unreachable node; the volatile `x-response-time` header is dropped. Failures that no offline
/// request can reach are rendered from the server's error type; the remaining foundation
/// variants share the same fallback arm as `lower: io`. Names describe behaviour, so a refactor
/// of how errors are built keeps the names and the diff shows exactly which responses changed.
pub(crate) fn render_errors(plugins: &AllPlugins) -> Result<Snapshot> {
    let runtime = Builder::new_multi_thread().enable_all().build()?;
    let data = tempdir()?;
    let mut out =
        String::from("# Generated by `cargo api` (crates/bitview_devtools). Do not edit.\n");
    runtime.block_on(async {
        let query = AsyncQuery::build(&plugins.defaults, None);
        let app = app(
            &query,
            ServerConfig {
                bind: IpAddr::V4(Ipv4Addr::LOCALHOST),
                port: Port::DEFAULT,
                data_path: data.path().to_path_buf(),
                website: Website::Disabled,
                cdn_cache_mode: CdnCacheMode::default(),
                max_weight: DEFAULT_MAX_WEIGHT,
                max_utxos: DEFAULT_MAX_UTXOS,
            },
        )
        .await?;
        for (name, method, uri, body) in requests() {
            let request = Request::builder()
                .method(method)
                .uri(uri)
                .body(Body::from(body))
                .map_err(|_| Error::Internal("invalid scenario request"))?;
            let Ok(response) = app.clone().oneshot(request).await;
            render(&mut out, name, response).await?;
        }
        for (name, error) in errors() {
            render(&mut out, name, error.into_response()).await?;
        }
        Ok::<_, Error>(())
    })?;
    runtime.shutdown_background();
    Ok(Snapshot {
        file: "errors.txt",
        contents: out,
    })
}

async fn render(out: &mut String, name: &str, response: Response<Body>) -> Result<()> {
    let (parts, body) = response.into_parts();
    let body = to_bytes(body, usize::MAX)
        .await
        .map_err(|_| Error::Internal("unreadable error body"))?;
    let mut headers = parts
        .headers
        .iter()
        .filter(|(key, _)| key.as_str() != "x-response-time")
        .map(|(key, value)| format!("{key}: {}", value.to_str().unwrap_or("<binary>")))
        .collect::<Vec<_>>();
    headers.sort();
    out.push_str(&format!("\n## {name}\n{}\n", parts.status));
    for header in headers {
        out.push_str(&header);
        out.push('\n');
    }
    out.push_str(&String::from_utf8_lossy(&body));
    out.push('\n');
    Ok(())
}

fn requests() -> Vec<(&'static str, Method, String, Vec<u8>)> {
    let get = |name: &'static str, uri: String| (name, Method::GET, uri, Vec::new());
    let post =
        |name: &'static str, uri: &str, body: Vec<u8>| (name, Method::POST, uri.into(), body);
    vec![
        // Rejected before any handler runs.
        get("request: invalid txid in path", "/api/tx/zz".into()),
        get(
            "request: invalid block hash in path",
            "/api/block/zz".into(),
        ),
        get(
            "request: invalid height in path",
            "/api/block-height/abc".into(),
        ),
        get(
            "request: query string on a path-only endpoint",
            "/api/blocks/tip/height?x=1".into(),
        ),
        get(
            "request: unknown index in series path",
            "/api/series/difficulty/notanindex".into(),
        ),
        get(
            "request: invalid timestamp parameter",
            "/api/v1/historical-price?timestamp=abc".into(),
        ),
        get(
            "request: unknown mining pool",
            "/api/v1/mining/pool/notapool".into(),
        ),
        get(
            "request: series bulk without series parameter",
            "/api/series/bulk?index=day1".into(),
        ),
        post(
            "request: wrong method",
            "/api/blocks/tip/height",
            Vec::new(),
        ),
        get("request: unknown API endpoint", "/api/nope".into()),
        get("request: unknown page", "/nope".into()),
        post(
            "request: broadcast body too large",
            "/api/tx",
            vec![b'0'; 8_000_001],
        ),
        post(
            "request: broadcast body not UTF-8",
            "/api/tx",
            vec![0xff, 0xfe],
        ),
        // Answered by a handler over empty data.
        post("broadcast body not hex", "/api/tx", b"zz".to_vec()),
        get("invalid address", "/api/address/notanaddress".into()),
        get(
            "invalid network",
            "/api/address/tb1qw508d6qejxtdg4y5r3zarvary0c5xw7kxpjzsx".into(),
        ),
        get("unknown block", format!("/api/block/{HASH}")),
        (
            "unknown block (HEAD)",
            Method::HEAD,
            format!("/api/block/{HASH}"),
            Vec::new(),
        ),
        get(
            "block height out of range",
            "/api/block-height/999999999".into(),
        ),
        get("unknown txid", format!("/api/tx/{HASH}")),
        get(
            "transaction index out of range",
            "/api/tx-index/999999999".into(),
        ),
        get("unknown address", format!("/api/address/{ADDRESS}")),
        get(
            "unknown address utxos",
            format!("/api/address/{ADDRESS}/utxo"),
        ),
        get(
            "unsupported address type",
            "/api/address/hash-prefix/p2ms/abcd".into(),
        ),
        get(
            "invalid address hash prefix",
            "/api/address/hash-prefix/p2wpkh/zz".into(),
        ),
        get("mempool unavailable", "/api/mempool".into()),
        get("mempool unavailable (recent)", "/api/mempool/recent".into()),
        get(
            "mempool unavailable (fees)",
            "/api/v1/fees/recommended".into(),
        ),
        get(
            "mempool unavailable (template diff)",
            "/api/v1/mempool/block-template/diff/1".into(),
        ),
        get("cpfp of unknown txid", format!("/api/v1/cpfp/{HASH}")),
        get(
            "reward stats over zero blocks",
            "/api/v1/mining/reward-stats/0".into(),
        ),
        get(
            "block by timestamp on empty chain",
            "/api/v1/mining/blocks/timestamp/0".into(),
        ),
        get("oracle price not computed", "/api/oracle/price".into()),
        get(
            "oracle histogram at height",
            "/api/oracle/histogram/outputs/100".into(),
        ),
        get("urpd without history", "/api/urpd/all".into()),
        get("urpd of unknown cohort", "/api/urpd/nocohort/100".into()),
        get("urpd at a point", "/api/urpd/all/100".into()),
        get("unindexable date", "/api/urpd/all/2008-12-31".into()),
        get(
            "series not found (suggestions)",
            "/api/series/difficulty_hashrat/day1".into(),
        ),
        get(
            "series not found (no suggestions)",
            "/api/series/zzzzzzzzzzzz/day1".into(),
        ),
        get(
            "series not found (long name)",
            format!("/api/series/{}/day1", "x".repeat(150)),
        ),
        get(
            "series unsupported index",
            "/api/series/blockhash/day1".into(),
        ),
        get(
            "series date range on tx_index",
            "/api/series/txid/tx_index?start=2020-01-01".into(),
        ),
        get(
            "series bulk with empty series",
            "/api/series/bulk?series=&index=day1".into(),
        ),
        get("no data", "/api/series/blockhash/height/latest".into()),
    ]
}

/// Conditions no offline request reaches, rendered from the server's error type. The server's
/// own messages are copied from their call sites, so these pin the mapping, not the wording.
fn errors() -> Vec<(&'static str, ServerError)> {
    let json = serde_json::from_str::<u8>("x").unwrap_err();
    let brk = |name: &'static str, error: Error| (name, ServerError::from(error));
    vec![
        // Failures below the API layer.
        brk("lower: io", Error::IO(io::Error::other("disk"))),
        brk("lower: internal", Error::Internal("invariant broken")),
        brk(
            "lower: not found",
            Error::NotFound("blk file missing".into()),
        ),
        brk("lower: parse", Error::Parse("bad hex in block file".into())),
        brk(
            "lower: out of range",
            Error::OutOfRange("position past end".into()),
        ),
        brk(
            "lower: unsupported type",
            Error::UnsupportedType("op_return".into()),
        ),
        brk("lower: json", Error::SerdeJSON(json)),
        brk(
            "lower: no rpc credentials",
            Error::NoRpcCredentials {
                cookie: PathBuf::from("/btc/.cookie"),
            },
        ),
        // Node and API conditions.
        brk(
            "broadcast rejected by node",
            Error::Parse("bad-txns-inputs-missingorspent".into()),
        ),
        brk(
            "weight exceeded",
            Error::WeightExceeded {
                requested: 10,
                max: 5,
            },
        ),
        brk("too many utxos", Error::TooManyUtxos),
        brk("query read timeout", Error::ReadTimeout),
        // Built by the server itself.
        ("request deadline (POST)", ServerError::timeout(true)),
        ("request deadline (GET)", ServerError::timeout(false)),
        (
            "broadcast queue full",
            ServerError::overloaded("too many pending transaction submissions"),
        ),
        ("handler panic", ServerError::internal("Unknown panic")),
    ]
}
