use std::{
    collections::BTreeMap,
    fs::{self, File},
    io::Read,
    path::Path,
};

use bitview_runtime::PluginSet;
use brk_error::Result;
use vecdb::{Database, Header};

use crate::{Imported, Snapshot};

/// Files up to this size are shown in full: they are version and marker files.
const FULL_BYTES: u64 = 64;
/// Larger files show their size and leading bytes (magic and format version).
const LEADING_BYTES: u64 = 16;

/// Plugin ids and root versions, every traversable vector (hidden included), and what a fresh
/// import leaves on disk: rawdb databases, regions (byte length, plus the header when one decodes),
/// and every other file.
pub fn render_surface(imported: Imported) -> Result<Vec<Snapshot>> {
    let Imported { plugins, dir } = imported;

    let mut out =
        String::from("# Generated by `cargo surface` (crates/bitview_devtools). Do not edit.\n");
    out.push_str("\n## Plugins: id, root version\n");
    let mut vecs = BTreeMap::<String, Vec<String>>::new();
    plugins.for_each_plugin(&mut |plugin| {
        out.push_str(&format!(
            "{}\t{}\n",
            plugin.id(),
            plugin.storage().schema_version()
        ));
        let lines = vecs.entry(plugin.id().to_string()).or_default();
        plugin.for_each_exportable(&mut |vec| {
            lines.push(format!(
                "{}\t{}\t{}\t{}\t{}",
                vec.name(),
                vec.index_type_to_string(),
                vec.value_type_to_string(),
                vec.version(),
                vec.region_names().join(","),
            ));
        });
    });
    for (plugin, lines) in &mut vecs {
        lines.sort();
        out.push_str(&format!(
            "\n## Vectors of {plugin}: name, index, value type, version, regions\n"
        ));
        for line in lines.iter() {
            out.push_str(line);
            out.push('\n');
        }
    }

    // Release every database before reopening them from disk.
    drop(plugins);
    out.push_str(
        "\n## Disk: databases (file sizes), regions (byte length, header when current), other files\n",
    );
    walk_disk(dir.path(), dir.path(), &mut out)?;

    Ok(vec![Snapshot {
        file: "surface.txt",
        contents: out,
    }])
}

fn walk_disk(root: &Path, dir: &Path, out: &mut String) -> Result<()> {
    let relative = |path: &Path| {
        path.strip_prefix(root)
            .unwrap_or(path)
            .display()
            .to_string()
    };
    let is_db = dir.join("data").is_file() && dir.join("regions").is_file();
    if is_db {
        let size = |name| fs::metadata(dir.join(name)).map(|metadata| metadata.len());
        out.push_str(&format!(
            "{}\tdatabase data={} regions={}\n",
            relative(dir),
            size("data")?,
            size("regions")?
        ));
        let db = Database::open(dir)?;
        for id in db.region_ids() {
            let Some(region) = db.get_region(&id) else {
                continue;
            };
            let mut line = format!("{} bytes", region.meta().byte_len());
            if let Some(header) = Header::read_unverified(&region)
                .ok()
                .filter(Header::is_current)
            {
                line.push_str(&format!(
                    ", header h{} v{} c{} {:?}",
                    header.header_version(),
                    header.vec_version(),
                    header.computed_version(),
                    header.format()
                ));
            }
            out.push_str(&format!("{}/{id}\t{line}\n", relative(dir)));
        }
    }

    let mut entries = fs::read_dir(dir)?
        .map(|entry| entry.map(|entry| entry.path()))
        .collect::<std::io::Result<Vec<_>>>()?;
    entries.sort();
    for path in entries {
        let name = path
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or_default();
        if is_db && (name == "data" || name == "regions") {
            continue;
        }
        if path.is_dir() {
            walk_disk(root, &path, out)?;
        } else {
            out.push_str(&format!("{}\t{}\n", relative(&path), describe_file(&path)?));
        }
    }
    Ok(())
}

fn describe_file(path: &Path) -> Result<String> {
    let len = fs::metadata(path)?.len();
    let full = len <= FULL_BYTES;
    let mut bytes = Vec::new();
    File::open(path)?
        .take(if full { len } else { LEADING_BYTES })
        .read_to_end(&mut bytes)?;
    let hex = bytes
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect::<String>();
    Ok(if full {
        format!("file {hex}")
    } else {
        format!("file {len} bytes, starts {hex}")
    })
}
