[package]
name = "bitview_plugin_rarity_meter"
description = "The Rarity Meter model plugin for Bitview"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage = "https://bitview.dev"
repository.workspace = true

[dependencies]
bitview_compute = { workspace = true }
bitview_plugin = { workspace = true }
bitview_plugin_bedrock = { workspace = true }
bitview_plugin_coinflow = { workspace = true }
bitview_plugin_cointime = { workspace = true }
bitview_plugin_distribution = { workspace = true }
bitview_plugin_mappings = { workspace = true }
bitview_plugin_price = { workspace = true }
brk_error = { workspace = true, features = ["vecdb"] }
bitview_plugin_indexer = { workspace = true }
bitview_traversable = { workspace = true }
brk_types = { workspace = true }
derive_more = { workspace = true }
rayon = { workspace = true }
schemars = { workspace = true }
vecdb = { workspace = true }
