[package]
name = "bitview_plugin_mining"
description = "The mining datasets plugin for Bitview"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage = "https://bitview.dev"
repository.workspace = true

[dependencies]
bitview_compute = { workspace = true }
bitview_plugin = { workspace = true }
bitview_plugin_blocks = { workspace = true }
bitview_plugin_mappings = { workspace = true }
bitview_plugin_price = { workspace = true }
bitview_plugin_transactions = { workspace = true }
brk_error = { workspace = true, features = ["vecdb"] }
bitview_plugin_indexer = { workspace = true }
bitview_traversable = { workspace = true }
brk_types = { workspace = true }
rayon = { workspace = true }
vecdb = { workspace = true }
