[package]
name = "bitview_vecs"
description = "Composable metric vectors and views for Bitview plugins"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage = "https://bitview.dev"
repository.workspace = true

[dependencies]
bitview_transforms = { workspace = true }
bitview_collections = { workspace = true, features = ["storage"] }
bitview_compute = { workspace = true }
brk_exit = { workspace = true }
rangeindex = { workspace = true }
bitview_cohort = { workspace = true, features = ["storage"] }
brk_error = { workspace = true, features = ["vecdb"] }
bitview_traversable = { workspace = true }
brk_types = { workspace = true, features = ["storage"] }
derive_more = { workspace = true }
rayon = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
vecdb = { workspace = true }
