[package]
name = "bitview_types"
description = "Query protocol and schema types shared throughout Bitview"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
brk_types = { workspace = true }
derive_more = { workspace = true }
indexmap = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
