[package]
name = "rawdb"
description = "Low-level, space-efficient storage engine with a filesystem-like API"
keywords = ["vec", "disk", "database"]
categories = ["database"]
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"

[dependencies]
libc = { workspace = true }
log = { workspace = true }
memmap2 = "0.9.11"
parking_lot = { workspace = true }
thiserror = "2.0.21"
rustc-hash = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[package.metadata.docs.rs]
all-features = true
