[package]
name = "bitview_runtime"
description = "The Bitview plugin lifecycle runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage = "https://bitview.dev"
repository.workspace = true
readme = "README.md"

[dependencies]
bitview_plugin = { workspace = true }
bitview_runtime_derive = { workspace = true }
brk_alloc = { workspace = true }
brk_error = { workspace = true }
tracing = { workspace = true }
vecdb = { workspace = true }

[dev-dependencies]
bitview_traversable = { workspace = true }
brk_types = { workspace = true }
tempfile = { workspace = true }
