#![doc = include_str!("../README.md")]

use hints::unlikely;

#[cfg(feature = "storage")]
pub use vecdb::{PrintableIndex, VecIndex, Version};

mod addr;
mod addr_bytes;
mod addr_mempool_stats;
mod bitcoin;
mod blk_metadata;
mod blk_position;
mod block;
mod block_targets;
mod block_template;
mod block_template_diff;
mod block_template_diff_entry;
mod blockhash;
mod bytes;
mod cents;
mod cents_sats;
mod cents_signed;
mod checked_sub;
mod coinbase_tag;
mod cpfp;
mod dollars;
mod feerate;
mod height;
mod hints;
mod histogram;
mod mempool_block;
mod mempool_entry_info;
mod mempool_info;
mod mempool_recent_tx;
mod next_block_hash;
mod outpoint;
mod outpoint_prefix;
mod output_type;
mod p2a_bytes;
mod p2pk33_bytes;
mod p2pk65_bytes;
mod p2pkh_bytes;
mod p2sh_bytes;
mod p2tr_bytes;
mod p2wpkh_bytes;
mod p2wsh_bytes;
mod percentile;
mod raw_locktime;
mod read_block;
mod recommended_fees;
mod sats;
mod sats_signed;
mod sigops;
mod store_value;
mod timestamp;
mod tx;
mod tx_index;
mod tx_status;
mod tx_version_raw;
mod txid;
mod txid_prefix;
mod txin;
mod txout;
mod txout_spend;
mod unit;
mod vin;
mod vout;
mod vsize;
mod weight;
mod witness;

pub use addr::*;
pub use addr_bytes::*;
pub use addr_mempool_stats::*;
pub use bitcoin::*;
pub use blk_metadata::*;
pub use blk_position::*;
pub use block::*;
pub use block_targets::*;
pub use block_template::*;
pub use block_template_diff::*;
pub use block_template_diff_entry::*;
pub use blockhash::*;
pub use bytes::*;
pub use cents::*;
pub use cents_sats::*;
pub use cents_signed::*;
pub use checked_sub::*;
pub use coinbase_tag::*;
pub use cpfp::*;
pub use dollars::*;
pub use feerate::*;
pub use height::*;
pub use histogram::*;
pub use mempool_block::*;
pub use mempool_entry_info::*;
pub use mempool_info::*;
pub use mempool_recent_tx::*;
pub use next_block_hash::*;
pub use outpoint::*;
pub use outpoint_prefix::*;
pub use output_type::*;
pub use p2a_bytes::*;
pub use p2pk33_bytes::*;
pub use p2pk65_bytes::*;
pub use p2pkh_bytes::*;
pub use p2sh_bytes::*;
pub use p2tr_bytes::*;
pub use p2wpkh_bytes::*;
pub use p2wsh_bytes::*;
pub use percentile::*;
pub use raw_locktime::*;
pub use read_block::*;
pub use recommended_fees::*;
pub use sats::*;
pub use sats_signed::*;
pub use sigops::*;
pub use store_value::*;
pub use timestamp::*;
pub use tx::*;
pub use tx_index::*;
pub use tx_status::*;
pub use tx_version_raw::*;
pub use txid::*;
pub use txid_prefix::*;
pub use txin::*;
pub use txout::*;
pub use txout_spend::*;
pub use unit::*;
pub use vin::*;
pub use vout::*;
pub use vsize::*;
pub use weight::*;
pub use witness::*;

#[cfg(test)]
mod tests;
