[package]
name = "bitview_plugin_bedrock"
description = "The Bedrock model plugin for Bitview"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage = "https://bitview.dev"
repository.workspace = true

[dependencies]
bitview_compute = { workspace = true }
bitview_urpd = { workspace = true }
bitview_transforms = { workspace = true }
bitview_vecs = { workspace = true }
bitview_plugin = { workspace = true }
bitview_plugin_coinflow = { workspace = true }
bitview_plugin_cointime = { workspace = true }
bitview_plugin_distribution_age = { workspace = true }
bitview_plugin_mappings = { workspace = true }
bitview_cohort = { workspace = true, features = ["storage"] }
brk_error = { workspace = true, features = ["vecdb"] }
bitview_plugin_indexer = { workspace = true }
bitview_traversable = { workspace = true }
brk_types = { workspace = true, features = ["storage"] }
derive_more = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
vecdb = { workspace = true }

[dev-dependencies]
statedb = { workspace = true }
tempfile = { workspace = true }
