[package]
name = "bitview_plugin_indexer"
description = "The blockchain indexer plugin for Bitview"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage = "https://bitview.dev"
repository.workspace = true
readme = "README.md"

[dependencies]
bitcoin = { workspace = true }
bitview_plugin = { workspace = true }
bitview_cohort = { workspace = true }
brk_error = { workspace = true, features = ["fjall", "vecdb"] }
brk_exit = { workspace = true }
brk_logger = { workspace = true }
brk_reader = { workspace = true }
brk_rpc = { workspace = true }
brk_store = { workspace = true }
bitview_traversable = { workspace = true }
brk_types = { workspace = true }
fjall = { workspace = true }
parking_lot = { workspace = true }
rayon = { workspace = true }
rustc-hash = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
tracing = { workspace = true }
vecdb = { workspace = true }

[dev-dependencies]
brk_alloc = { workspace = true }
color-eyre = { workspace = true }
tempfile = { workspace = true }
