//! Scalar series values: one named type per meaning and representation, generated by
//! [`scalar!`]. Units (`Count`, `Bytes`, `Ratio`, ...) name what a value measures; the generic types
//! (`Float32`, `UInt64`, ...) cover values without a coherent unit.

/// Generates a scalar newtype over a primitive with storage, serde, schema and formatting.
///
/// `int` for unsigned and signed integers, `float` for `f32`/`f64`. Narrowing conversions saturate
/// and are checked in dev builds. Floats order NaN first and equal to itself, and write non-finite
/// values as JSON `null` / an empty CSV cell (an undefined value: `Formattable::UNDEFINED`).
macro_rules! scalar {
    ($(#[$meta:meta])* int $name:ident($repr:ty)) => {
        $(#[$meta])*
        #[derive(
            Debug,
            Default,
            Clone,
            Copy,
            PartialEq,
            Eq,
            PartialOrd,
            Ord,
            Hash,
            ::derive_more::Deref,
            ::serde::Serialize,
            ::serde::Deserialize,
            ::schemars::JsonSchema,
        )]
        #[cfg_attr(feature = "storage", derive(::vecdb::Pco))]
        pub struct $name($repr);

        impl $name {
            pub const ZERO: Self = Self(0);
            pub const MAX: Self = Self(<$repr>::MAX);

            #[inline]
            pub const fn new(value: $repr) -> Self {
                Self(value)
            }
        }

        impl From<$repr> for $name {
            #[inline]
            fn from(value: $repr) -> Self {
                Self(value)
            }
        }

        impl From<$name> for $repr {
            #[inline]
            fn from(value: $name) -> Self {
                value.0
            }
        }

        /// Saturating: out-of-range values clamp, never wrap (checked in dev builds).
        impl From<usize> for $name {
            #[inline]
            fn from(value: usize) -> Self {
                debug_assert!(<$repr>::try_from(value).is_ok(), "{value} doesn't fit {}", stringify!($name));
                Self(<$repr>::try_from(value).unwrap_or(<$repr>::MAX))
            }
        }

        /// Saturating (`as` from a float clamps and maps NaN to zero; out of range is checked in
        /// dev builds).
        impl From<f64> for $name {
            #[inline]
            fn from(value: f64) -> Self {
                debug_assert!(
                    value.is_nan() || (<$repr>::MIN as f64..=<$repr>::MAX as f64).contains(&value),
                    "{value} doesn't fit {}",
                    stringify!($name)
                );
                Self(value as $repr)
            }
        }

        impl From<$name> for f64 {
            #[inline]
            fn from(value: $name) -> Self {
                value.0 as f64
            }
        }

        impl ::brk_types::CheckedSub for $name {
            #[inline]
            fn checked_sub(self, rhs: Self) -> Option<Self> {
                self.0.checked_sub(rhs.0).map(Self)
            }
        }

        #[cfg(feature = "storage")]
        impl ::vecdb::CheckedSub for $name {
            #[inline]
            fn checked_sub(self, rhs: Self) -> Option<Self> {
                self.0.checked_sub(rhs.0).map(Self)
            }
        }

        impl ::std::ops::Add for $name {
            type Output = Self;
            #[inline]
            fn add(self, rhs: Self) -> Self {
                Self(self.0 + rhs.0)
            }
        }

        impl ::std::ops::AddAssign for $name {
            #[inline]
            fn add_assign(&mut self, rhs: Self) {
                self.0 += rhs.0;
            }
        }

        impl ::std::ops::Sub for $name {
            type Output = Self;
            #[inline]
            fn sub(self, rhs: Self) -> Self {
                Self(self.0 - rhs.0)
            }
        }

        impl ::std::ops::SubAssign for $name {
            #[inline]
            fn sub_assign(&mut self, rhs: Self) {
                self.0 -= rhs.0;
            }
        }

        impl ::std::iter::Sum for $name {
            fn sum<I: Iterator<Item = Self>>(iter: I) -> Self {
                Self(iter.map(|value| value.0).sum())
            }
        }

        /// Division by a count (in `i128`, so any count works); zero when dividing by zero.
        impl ::std::ops::Div<usize> for $name {
            type Output = Self;
            #[inline]
            fn div(self, rhs: usize) -> Self {
                debug_assert!(rhs != 0, "{} divided by zero", stringify!($name));
                if rhs == 0 {
                    Self::ZERO
                } else {
                    Self((i128::from(self.0) / rhs as i128) as $repr)
                }
            }
        }

        impl ::std::fmt::Display for $name {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str(::itoa::Buffer::new().format(self.0))
            }
        }

        #[cfg(feature = "storage")]
        impl ::vecdb::Formattable for $name {
            #[inline(always)]
            fn write_to(&self, buf: &mut Vec<u8>) {
                buf.extend_from_slice(::itoa::Buffer::new().format(self.0).as_bytes());
            }
        }
    };

    ($(#[$meta:meta])* float $name:ident(f32)) => {
        $crate::scalar::scalar!(@float $(#[$meta])* $name(f32));

        /// Narrowing; the value must fit `f32` (checked in dev builds).
        impl From<f64> for $name {
            #[inline]
            fn from(value: f64) -> Self {
                debug_assert!(
                    value.is_nan() || (f32::MIN as f64..=f32::MAX as f64).contains(&value),
                    "{value} doesn't fit {}",
                    stringify!($name)
                );
                Self(value as f32)
            }
        }

        impl From<$name> for f64 {
            #[inline]
            fn from(value: $name) -> Self {
                f64::from(value.0)
            }
        }
    };

    ($(#[$meta:meta])* float $name:ident(f64)) => {
        $crate::scalar::scalar!(@float $(#[$meta])* $name(f64));
    };

    (@float $(#[$meta:meta])* $name:ident($repr:ty)) => {
        $(#[$meta])*
        #[derive(
            Debug,
            Default,
            Clone,
            Copy,
            ::derive_more::Deref,
            ::serde::Serialize,
            ::serde::Deserialize,
            ::schemars::JsonSchema,
        )]
        #[cfg_attr(feature = "storage", derive(::vecdb::Pco))]
        pub struct $name($repr);

        impl $name {
            pub const ZERO: Self = Self(0.0);
            pub const NAN: Self = Self(<$repr>::NAN);

            #[inline]
            pub const fn new(value: $repr) -> Self {
                Self(value)
            }

            #[inline]
            pub fn is_nan(self) -> bool {
                self.0.is_nan()
            }
        }

        impl From<$repr> for $name {
            #[inline]
            fn from(value: $repr) -> Self {
                Self(value)
            }
        }

        impl From<$name> for $repr {
            #[inline]
            fn from(value: $name) -> Self {
                value.0
            }
        }

        impl From<usize> for $name {
            #[inline]
            fn from(value: usize) -> Self {
                Self(value as $repr)
            }
        }

        impl ::brk_types::CheckedSub for $name {
            #[inline]
            fn checked_sub(self, rhs: Self) -> Option<Self> {
                Some(Self(self.0 - rhs.0))
            }
        }

        #[cfg(feature = "storage")]
        impl ::vecdb::CheckedSub for $name {
            #[inline]
            fn checked_sub(self, rhs: Self) -> Option<Self> {
                Some(Self(self.0 - rhs.0))
            }
        }

        impl ::std::ops::Add for $name {
            type Output = Self;
            #[inline]
            fn add(self, rhs: Self) -> Self {
                Self(self.0 + rhs.0)
            }
        }

        impl ::std::ops::AddAssign for $name {
            #[inline]
            fn add_assign(&mut self, rhs: Self) {
                self.0 += rhs.0;
            }
        }

        impl ::std::ops::Sub for $name {
            type Output = Self;
            #[inline]
            fn sub(self, rhs: Self) -> Self {
                Self(self.0 - rhs.0)
            }
        }

        impl ::std::ops::SubAssign for $name {
            #[inline]
            fn sub_assign(&mut self, rhs: Self) {
                self.0 -= rhs.0;
            }
        }

        impl ::std::ops::Neg for $name {
            type Output = Self;
            #[inline]
            fn neg(self) -> Self {
                Self(-self.0)
            }
        }

        impl ::std::iter::Sum for $name {
            fn sum<I: Iterator<Item = Self>>(iter: I) -> Self {
                Self(iter.map(|value| value.0).sum())
            }
        }

        /// Division by a count; NaN when dividing by zero.
        impl ::std::ops::Div<usize> for $name {
            type Output = Self;
            #[inline]
            fn div(self, rhs: usize) -> Self {
                if rhs == 0 { Self::NAN } else { Self(self.0 / rhs as $repr) }
            }
        }

        impl PartialEq for $name {
            fn eq(&self, other: &Self) -> bool {
                match (self.0.is_nan(), other.0.is_nan()) {
                    (true, true) => true,
                    (false, false) => self.0 == other.0,
                    _ => false,
                }
            }
        }

        impl Eq for $name {}

        impl PartialOrd for $name {
            fn partial_cmp(&self, other: &Self) -> Option<::std::cmp::Ordering> {
                Some(self.cmp(other))
            }
        }

        /// NaN orders first.
        impl Ord for $name {
            fn cmp(&self, other: &Self) -> ::std::cmp::Ordering {
                match (self.0.is_nan(), other.0.is_nan()) {
                    (true, true) => ::std::cmp::Ordering::Equal,
                    (true, false) => ::std::cmp::Ordering::Less,
                    (false, true) => ::std::cmp::Ordering::Greater,
                    (false, false) => self.0.partial_cmp(&other.0).unwrap(),
                }
            }
        }

        impl ::std::fmt::Display for $name {
            fn fmt(&self, f: &mut ::std::fmt::Formatter<'_>) -> ::std::fmt::Result {
                f.write_str(::ryu::Buffer::new().format(self.0))
            }
        }

        #[cfg(feature = "storage")]
        impl ::vecdb::Formattable for $name {
            const UNDEFINED: bool = true;

            /// Non-finite: an empty CSV cell.
            #[inline(always)]
            fn write_to(&self, buf: &mut Vec<u8>) {
                if self.0.is_finite() {
                    buf.extend_from_slice(::ryu::Buffer::new().format_finite(self.0).as_bytes());
                }
            }

            /// One finiteness check on the hot path.
            #[inline(always)]
            fn fmt_json(&self, buf: &mut Vec<u8>) {
                if self.0.is_finite() {
                    buf.extend_from_slice(::ryu::Buffer::new().format_finite(self.0).as_bytes());
                } else {
                    buf.extend_from_slice(b"null");
                }
            }
        }
    };
}

pub(crate) use scalar;
