//! Series value types named by what they measure, generated by [`scalar!`](crate::scalar::scalar);
//! generic types (`Float32`, ...) cover values without a coherent unit.

use std::ops::{Div, Mul};

use brk_types::{Cents, Height, Sats, SigOps, TxIndex, Weight};

use crate::{TxInIndex, TxOutIndex, scalar::scalar};

scalar! {
    /// A signed model score.
    int Score(i8)
}

scalar! {
    /// A discrete rank.
    int Rank(u8)
}

scalar! {
    /// A 32-bit floating-point value without a specific unit.
    float Float32(f32)
}

scalar! {
    /// A 64-bit floating-point value without a specific unit.
    float Float64(f64)
}

scalar! {
    /// Bitcoin multiplied by the days it was held.
    float CoinDays(f64)
}

scalar! {
    /// Bitcoin multiplied by the blocks it was held.
    float CoinBlocks(f64)
}

scalar! {
    /// Bitcoin multiplied by the years it was held.
    float CoinYears(f64)
}

scalar! {
    /// A duration in days.
    float Days(f32)
}

scalar! {
    /// A duration in years.
    float Years(f32)
}

scalar! {
    /// Hashes per second.
    float Hashrate(f64)
}

scalar! {
    /// Proof-of-work difficulty.
    float Difficulty(f64)
}

scalar! {
    /// A fraction per day.
    float PerDay(f64)
}

scalar! {
    /// A USD amount (32-bit stored form).
    float Dollars32(f32)
}

scalar! {
    /// Events per second.
    float PerSecond(f32)
}

scalar! {
    /// A mean number of things.
    float CountFract(f32)
}

scalar! {
    /// A mean size in bytes.
    float BytesFract(f32)
}

scalar! {
    /// A mean virtual size in vbytes.
    float VSizeFract(f32)
}

scalar! {
    /// A mean weight in weight units.
    float WeightFract(f32)
}

scalar! {
    /// A mean BIP-141 signature-operation cost.
    float SigOpsFract(f32)
}

scalar! {
    /// A mean duration in seconds.
    float SecondsFract(f32)
}

scalar! {
    /// A mean amount in cents.
    float CentsFract(f64)
}

scalar! {
    /// A dimensionless ratio: a quotient, share or multiple.
    float Ratio(f32)
}

scalar! {
    /// A dimensionless ratio at double precision.
    float Ratio64(f64)
}

scalar! {
    /// A percentage: a ratio times 100.
    float Percent(f32)
}

scalar! {
    /// A percentage at double precision, for sums of percentages.
    float Percent64(f64)
}

scalar! {
    /// A number of things.
    int Count(u64)
}

scalar! {
    /// A number of things that fits 16 bits (at most 65,535), such as transactions per block.
    int Count16(u16)
}

scalar! {
    /// A number of things that fits 32 bits, such as outputs per block.
    int Count32(u32)
}

scalar! {
    /// A change in a number of things.
    int CountSigned(i64)
}

scalar! {
    /// A size in bytes.
    int Bytes(u64)
}

scalar! {
    /// A size in bytes that fits 32 bits (under 4 GiB), such as a block or transaction size.
    int Bytes32(u32)
}

scalar! {
    /// A duration in seconds (at most about 136 years).
    int Seconds(u32)
}

scalar! {
    /// Weight in weight units with enough range for cumulative and rolling totals.
    int Weight64(u64)
}

scalar! {
    /// BIP-141 signature-operation cost with enough range for cumulative and rolling totals.
    int SigOps64(u64)
}

impl From<Count32> for Count {
    #[inline]
    fn from(value: Count32) -> Self {
        Self(u64::from(value.0))
    }
}

impl From<Count16> for Count {
    #[inline]
    fn from(value: Count16) -> Self {
        Self(u64::from(value.0))
    }
}

impl From<Bytes32> for Bytes {
    #[inline]
    fn from(value: Bytes32) -> Self {
        Self(u64::from(value.0))
    }
}

impl From<Percent> for Percent64 {
    #[inline]
    fn from(value: Percent) -> Self {
        Self(f64::from(value.0))
    }
}

impl From<Weight> for Weight64 {
    #[inline]
    fn from(value: Weight) -> Self {
        Self(u64::from(value))
    }
}

impl From<SigOps> for SigOps64 {
    #[inline]
    fn from(value: SigOps) -> Self {
        Self(u64::from(u32::from(value)))
    }
}

/// A position or a difference of positions counts the things an index enumerates.
macro_rules! count_from_index {
    ($($index:ty),+) => {$(
        impl From<$index> for Count {
            #[inline]
            fn from(value: $index) -> Self {
                Self(u64::from(*value))
            }
        }
    )+};
}

count_from_index!(Height, TxIndex, TxInIndex, TxOutIndex);

impl From<Count> for usize {
    #[inline]
    fn from(value: Count) -> Self {
        value.0 as usize
    }
}

/// The average amount per thing; zero when there are none.
impl Div<Count> for Sats {
    type Output = Self;

    #[inline]
    fn div(self, rhs: Count) -> Self {
        Self::from(u64::from(self).checked_div(rhs.0).unwrap_or(0))
    }
}

/// Ratios multiply into ratios.
impl Mul for Ratio64 {
    type Output = Self;

    #[inline]
    fn mul(self, rhs: Self) -> Self {
        Self(self.0 * rhs.0)
    }
}

/// An amount scaled by a ratio.
impl Mul<Ratio64> for Sats {
    type Output = Self;

    #[inline]
    fn mul(self, rhs: Ratio64) -> Self {
        self * rhs.0
    }
}

impl Mul<Sats> for Ratio64 {
    type Output = Sats;

    #[inline]
    fn mul(self, rhs: Sats) -> Sats {
        rhs * self
    }
}

impl Mul<Ratio64> for Cents {
    type Output = Self;

    #[inline]
    fn mul(self, rhs: Ratio64) -> Self {
        Self::from(f64::from(self) * rhs.0)
    }
}

impl Mul<Cents> for Ratio64 {
    type Output = Cents;

    #[inline]
    fn mul(self, rhs: Cents) -> Cents {
        rhs * self
    }
}
