//! Series value types named by what they measure, generated by [`scalar!`](crate::scalar::scalar);
//! generic types (`Float32`, ...) cover values without a coherent unit.

use std::ops::Div;

use brk_types::{Height, Sats, SigOps, TxIndex};

use crate::{TxInIndex, TxOutIndex, scalar::scalar};

scalar! {
    /// A signed model score.
    int Score(i8)
}

scalar! {
    /// A discrete rank.
    int Rank(u8)
}

scalar! {
    /// A 32-bit floating-point value without a specific unit.
    float Float32(f32)
}

scalar! {
    /// A number of things.
    int Count(u64)
}

scalar! {
    /// A number of things that fits 16 bits (at most 65,535), such as transactions per block.
    int Count16(u16)
}

scalar! {
    /// A change in a number of things.
    int CountSigned(i64)
}

scalar! {
    /// A size in bytes.
    int Bytes(u64)
}

scalar! {
    /// A size in bytes that fits 32 bits (under 4 GiB), such as a block or transaction size.
    int Bytes32(u32)
}

scalar! {
    /// BIP-141 signature-operation cost with enough range for cumulative and rolling totals.
    int SigOps64(u64)
}

impl From<Count16> for Count {
    #[inline]
    fn from(value: Count16) -> Self {
        Self(u64::from(value.0))
    }
}

impl From<Bytes32> for Bytes {
    #[inline]
    fn from(value: Bytes32) -> Self {
        Self(u64::from(value.0))
    }
}

impl From<SigOps> for SigOps64 {
    #[inline]
    fn from(value: SigOps) -> Self {
        Self(u64::from(u32::from(value)))
    }
}

/// A position or a difference of positions counts the things an index enumerates.
macro_rules! count_from_index {
    ($($index:ty),+) => {$(
        impl From<$index> for Count {
            #[inline]
            fn from(value: $index) -> Self {
                Self(u64::from(*value))
            }
        }
    )+};
}

count_from_index!(Height, TxIndex, TxInIndex, TxOutIndex);

impl From<Count> for usize {
    #[inline]
    fn from(value: Count) -> Self {
        value.0 as usize
    }
}

/// The average amount per thing; zero when there are none.
impl Div<Count> for Sats {
    type Output = Self;

    #[inline]
    fn div(self, rhs: Count) -> Self {
        Self::from(u64::from(self).checked_div(rhs.0).unwrap_or(0))
    }
}
