//! Series value types named by what they measure, generated by [`scalar!`](crate::scalar::scalar);
//! generic types (`Float32`, ...) cover values without a coherent unit.

use crate::scalar::scalar;

scalar! {
    /// A signed model score.
    int Score(i8)
}

scalar! {
    /// A discrete rank.
    int Rank(u8)
}

scalar! {
    /// A 32-bit floating-point value without a specific unit.
    float Float32(f32)
}
