use brk_types::{
    Date, Day1, Day3, Epoch, Halving, Height, Hour1, Hour4, Hour12, Minute10, Minute30, Month1,
    Month3, Month6, StoredU64, Timestamp, Week1, Year1, Year10,
};
use vecdb::{CachedBoxedVec, ReadableBoxedVec};

use crate::{LazyPreviousDeltaVec, PerResolution};

#[derive(Clone)]
pub struct IndexSources {
    pub first_height: PerResolution<
        ReadableBoxedVec<Minute10, Height>,
        ReadableBoxedVec<Minute30, Height>,
        ReadableBoxedVec<Hour1, Height>,
        ReadableBoxedVec<Hour4, Height>,
        ReadableBoxedVec<Hour12, Height>,
        ReadableBoxedVec<Day1, Height>,
        ReadableBoxedVec<Day3, Height>,
        ReadableBoxedVec<Week1, Height>,
        ReadableBoxedVec<Month1, Height>,
        ReadableBoxedVec<Month3, Height>,
        ReadableBoxedVec<Month6, Height>,
        ReadableBoxedVec<Year1, Height>,
        ReadableBoxedVec<Year10, Height>,
        ReadableBoxedVec<Halving, Height>,
        ReadableBoxedVec<Epoch, Height>,
    >,
    pub cached_first_height: PerResolution<
        CachedBoxedVec<Minute10, Height>,
        CachedBoxedVec<Minute30, Height>,
        CachedBoxedVec<Hour1, Height>,
        CachedBoxedVec<Hour4, Height>,
        CachedBoxedVec<Hour12, Height>,
        CachedBoxedVec<Day1, Height>,
        CachedBoxedVec<Day3, Height>,
        CachedBoxedVec<Week1, Height>,
        CachedBoxedVec<Month1, Height>,
        CachedBoxedVec<Month3, Height>,
        CachedBoxedVec<Month6, Height>,
        CachedBoxedVec<Year1, Height>,
        CachedBoxedVec<Year10, Height>,
        CachedBoxedVec<Halving, Height>,
        CachedBoxedVec<Epoch, Height>,
    >,
    pub timestamp: PerResolution<
        ReadableBoxedVec<Minute10, Timestamp>,
        ReadableBoxedVec<Minute30, Timestamp>,
        ReadableBoxedVec<Hour1, Timestamp>,
        ReadableBoxedVec<Hour4, Timestamp>,
        ReadableBoxedVec<Hour12, Timestamp>,
        ReadableBoxedVec<Day1, Timestamp>,
        ReadableBoxedVec<Day3, Timestamp>,
        ReadableBoxedVec<Week1, Timestamp>,
        ReadableBoxedVec<Month1, Timestamp>,
        ReadableBoxedVec<Month3, Timestamp>,
        ReadableBoxedVec<Month6, Timestamp>,
        ReadableBoxedVec<Year1, Timestamp>,
        ReadableBoxedVec<Year10, Timestamp>,
        ReadableBoxedVec<Halving, Timestamp>,
        ReadableBoxedVec<Epoch, Timestamp>,
    >,
    pub height_minute10: ReadableBoxedVec<Height, Minute10>,
    pub height_day1: ReadableBoxedVec<Height, Day1>,
    pub height_tx_index_count: LazyPreviousDeltaVec<Height, StoredU64>,
    pub day3_date: ReadableBoxedVec<Day3, Date>,
    pub week1_date: ReadableBoxedVec<Week1, Date>,
    pub month1_date: ReadableBoxedVec<Month1, Date>,
    pub month3_date: ReadableBoxedVec<Month3, Date>,
    pub month6_date: ReadableBoxedVec<Month6, Date>,
    pub year1_date: ReadableBoxedVec<Year1, Date>,
    pub year10_date: ReadableBoxedVec<Year10, Date>,
}
