[package]
name = "vecdb"
description = "High-performance mutable persistent vectors built on rawdb"
keywords = ["vec", "disk", "database"]
categories = ["database"]
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"

[features]
derive = ["vecdb_derive"]
lz4 = ["dep:lz4_flex"]
pco = ["dep:pco"]
schemars = ["dep:schemars"]
serde = ["dep:serde"]
zerocopy = ["dep:zerocopy"]
zstd = ["dep:zstd"]

[dependencies]
brk_exit = { workspace = true }
itoa = "1.0.18"
libc = { workspace = true }
log = { workspace = true }
parking_lot = { workspace = true }
rawdb = { workspace = true }
rayon = { workspace = true }
ryu = "1.0.23"
thiserror = "2"

# [optional-dependencies]
lz4_flex = { workspace = true, optional = true }
pco = { workspace = true, optional = true }
schemars = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"], optional = true }
vecdb_derive = { workspace = true, optional = true }
zerocopy = { version = "0.8.58", features = ["zerocopy-derive"], optional = true }
zstd = { version = "0.14.0", optional = true }

[dev-dependencies]
tempfile = { workspace = true }

[package.metadata.docs.rs]
all-features = true
