[package]
name = "bitview_compute"
description = "Calculation algorithms for Bitview plugins"
version.workspace = true
edition.workspace = true
license.workspace = true
homepage = "https://bitview.dev"
repository.workspace = true

[dependencies]
rayon = { workspace = true }
bitview_transforms = { workspace = true }
bitview_collections = { workspace = true }
brk_exit = { workspace = true }
bitview_cohort = { workspace = true }
brk_error = { workspace = true, features = ["vecdb"] }
brk_types = { workspace = true, features = ["storage"] }
schemars = { workspace = true }
serde = { workspace = true }
vecdb = { workspace = true }
