//! Rust command catalog generation for `bitview-cli`.

use std::{collections::BTreeSet, fmt::Write, io, path::Path};

use crate::{Endpoint, generators::write_if_changed};

/// Generate the OpenAPI-derived command catalog used by `bitview-cli`.
pub fn generate_cli(endpoints: &[Endpoint], output_path: &Path) -> io::Result<()> {
    let mut commands = endpoints
        .iter()
        .filter(|endpoint| !endpoint.deprecated)
        .map(|endpoint| (to_kebab_case(&endpoint.operation_name()), endpoint))
        .collect::<Vec<_>>();
    commands.sort_by(|(left, _), (right, _)| left.cmp(right));

    validate_commands(&commands)?;

    let mut output = String::from(
        "// Auto-generated by bitview_bindgen. Do not edit.\n\n\
         use crate::{command::Command, parameter::Parameter, request_body::RequestBody};\n\n\
         #[rustfmt::skip]\n\
         pub(crate) static COMMANDS: &[Command] = &[\n",
    );

    for (name, endpoint) in commands {
        writeln!(output, "    Command {{").unwrap();
        writeln!(output, "        name: {name:?},").unwrap();
        writeln!(output, "        method: {:?},", endpoint.method).unwrap();
        writeln!(output, "        path: {:?},", endpoint.path).unwrap();
        writeln!(
            output,
            "        summary: {:?},",
            endpoint.summary.as_deref().unwrap_or("")
        )
        .unwrap();
        writeln!(
            output,
            "        description: {:?},",
            endpoint.description.as_deref().unwrap_or("")
        )
        .unwrap();
        write_parameters(&mut output, "path_parameters", &endpoint.path_params);
        write_parameters(&mut output, "query_parameters", &endpoint.query_params);
        match &endpoint.request_body {
            Some(body) => writeln!(
                output,
                "        request_body: Some(RequestBody {{ value_name: {:?}, required: {}, content_type: {:?} }}),",
                body.body_type, body.required, body.content_type
            )
            .unwrap(),
            None => writeln!(output, "        request_body: None,").unwrap(),
        }
        writeln!(output, "    }},").unwrap();
    }
    output.push_str("];\n");

    write_if_changed(output_path, &output)
}

fn write_parameters(output: &mut String, field: &str, parameters: &[crate::Parameter]) {
    writeln!(output, "        {field}: &[").unwrap();
    for parameter in parameters {
        writeln!(
            output,
            "            Parameter {{ api_name: {:?}, name: {:?}, required: {}, value_name: {:?}, repeatable: {}, description: {:?} }},",
            parameter.name,
            to_kebab_case(&parameter.name),
            parameter.required,
            parameter.param_type,
            parameter.param_type.ends_with("[]"),
            parameter.description
        )
        .unwrap();
    }
    writeln!(output, "        ],").unwrap();
}

fn validate_commands(commands: &[(String, &Endpoint)]) -> io::Result<()> {
    let mut names = BTreeSet::new();
    for (name, endpoint) in commands {
        if name.is_empty() {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!(
                    "empty CLI command name for {} {}",
                    endpoint.method, endpoint.path
                ),
            ));
        }
        if !names.insert(name) {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                format!("duplicate CLI command name: {name}"),
            ));
        }

        let mut flags = BTreeSet::new();
        for parameter in &endpoint.query_params {
            let flag = to_kebab_case(parameter.name.trim_end_matches("[]"));
            if !flags.insert(flag.clone()) {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidData,
                    format!("duplicate --{flag} flag for CLI command {name}"),
                ));
            }
        }
    }
    Ok(())
}

fn to_kebab_case(value: &str) -> String {
    let mut output = String::with_capacity(value.len());
    let mut previous_was_separator = true;
    let mut previous_was_lower_or_digit = false;

    for character in value.trim_end_matches("[]").chars() {
        if character.is_ascii_alphanumeric() {
            if character.is_ascii_uppercase()
                && previous_was_lower_or_digit
                && !output.ends_with('-')
            {
                output.push('-');
            }
            output.push(character.to_ascii_lowercase());
            previous_was_separator = false;
            previous_was_lower_or_digit =
                character.is_ascii_lowercase() || character.is_ascii_digit();
        } else if !previous_was_separator && !output.ends_with('-') {
            output.push('-');
            previous_was_separator = true;
            previous_was_lower_or_digit = false;
        }
    }

    output.trim_matches('-').to_owned()
}

#[cfg(test)]
mod tests {
    use super::to_kebab_case;

    #[test]
    fn command_and_flag_names_are_kebab_case() {
        assert_eq!(to_kebab_case("getBlockByHeight"), "get-block-by-height");
        assert_eq!(to_kebab_case("get_series_data"), "get-series-data");
        assert_eq!(to_kebab_case("txId[]"), "tx-id");
    }
}
